import{describe,it,expect}from'vitest';import{readFileSync}from'node:fs';import{fresh,string,integer}from'../src/model';import{BPETokenizer}from'../src/tokenizer';import{type AugmentConfig}from'../src/recipe';import{type AugmentCache,planAugmentation,runAugmentation,parseAugmentation,demoAugmentation}from'../src/augmentation';import{datasetCard,cardMarkdown,profileColumn,datasetDiff,tokenStats}from'../src/report';import{rawJSONL}from'../src/importers';import{detectPII}from'../src/quality';
const tok=new BPETokenizer(readFileSync('resources/cl100k_base.tiktoken','utf8'));const cfg:AugmentConfig={kind:'rewrite',column:'text',instruction:'',labels:[],concurrency:2,maxTokens:1024};
describe('optional bounded augmentation',()=>{
 it('plans unique pending requests and the full configured output cap',async()=>{const ds=fresh(['text'],[[string('Same passage')],[string('Same passage')],[string('')]]);const plan=await planAugmentation(cfg,ds,'provider-model',{},tok);expect(plan.calls).toBe(1);expect(plan.pending).toHaveLength(2);expect(plan.emptyRows).toBe(1);expect(plan.maxOutputTokens).toBe(1024);let calls=0;const run=await runAugmentation(cfg,ds,'provider-model',{},tok,async()=>{calls++;return 'Result';},{maxApprovedCalls:1});expect(calls).toBe(1);expect(run.dataset.records[0].values[1]).toEqual(string('Result'));expect(run.dataset.records[1].values[1]).toEqual(string('Result'));});
 it('preserves existing output columns and resumes from valid persisted responses',async()=>{const ds=fresh(['text','rewritten'],[[string('First passage'),string('Original output')],[string('Second passage'),string('Other original')]]),cache:AugmentCache=Object.create(null);let requests=0,saves=0;await expect(runAugmentation(cfg,ds,'host/model',cache,tok,async p=>{requests++;if(p.user.includes('Second'))throw Error('Temporary network failure');return 'First normalized';},{maxApprovedCalls:2,checkpoint:async()=>{saves++;}})).rejects.toThrow('cached for resume');expect(requests).toBe(2);expect(saves).toBe(1);const plan=await planAugmentation(cfg,ds,'host/model',cache,tok);expect(plan.calls).toBe(1);expect(plan.cached).toHaveLength(1);const done=await runAugmentation(cfg,ds,'host/model',cache,tok,async()=>{requests++;return 'Second normalized';},{maxApprovedCalls:1});expect(requests).toBe(3);expect(done.dataset.columns).toEqual(['text','rewritten','rewritten_2']);expect(done.dataset.records[0].values[1]).toEqual(string('Original output'));expect(ds.records[0].values).toHaveLength(2);});
 it('does not run a concurrent batch after a failed first request or retry automatically',async()=>{const ds=fresh(['text'],Array.from({length:10},(_,i)=>[string('row '+i)]));let calls=0;await expect(runAugmentation({...cfg,concurrency:8},ds,'host/model',{},tok,async()=>{calls++;throw Error('HTTP 401');},{maxApprovedCalls:10})).rejects.toThrow('Initial');expect(calls).toBe(1);});
 it('requires reviewed call limits and checks oversized inputs before any request',async()=>{const ds=fresh(['text'],[[string('small')],[string('a'.repeat(24001))]]);let calls=0;await expect(runAugmentation(cfg,ds,'host/model',{},tok,async()=>{calls++;return 'answer';},{maxApprovedCalls:2})).rejects.toThrow('Chunk');expect(calls).toBe(0);await expect(runAugmentation(cfg,fresh(['text'],[[string('x')]]),'host/model',{},tok,async()=>{calls++;return'answer';},{maxApprovedCalls:0})).rejects.toThrow('reviewed');expect(calls).toBe(0);});
 it('does not record a checkpoint as durable after a save failure',async()=>{const cache:AugmentCache={};await expect(runAugmentation(cfg,fresh(['text'],[[string('x')]]),'host/model',cache,tok,async()=>'rewritten',{maxApprovedCalls:1,checkpoint:async()=>{throw Error('Disk full');}})).rejects.toThrow('Disk full');expect(Object.keys(cache)).toHaveLength(0);});
 it('validates every structured response instead of fabricating fallback fields',()=>{expect(()=>parseAugmentation({...cfg,kind:'generateQA'},'{"answer":"only"}')).toThrow('question');expect(()=>parseAugmentation({...cfg,kind:'judgeScore'},'{"score":99,"rationale":"fine"}')).toThrow('1 to 10');expect(()=>parseAugmentation({...cfg,kind:'judgeScore'},'{"score":7.5,"rationale":"fine"}')).toThrow();expect(()=>parseAugmentation({...cfg,kind:'classify',labels:['one','two']},'{"label":"three"}')).toThrow('outside');expect(parseAugmentation({...cfg,kind:'generateQA'},'```json\n{"question":"Q","answer":"A"}\n```')).toEqual([string('Q'),string('A')]);});
 it('binds cached responses to provider, model and complete instructions',async()=>{const ds=fresh(['text'],[[string('A passage')]]),cache:AugmentCache={};await runAugmentation(cfg,ds,'one/model',cache,tok,async()=>'saved',{maxApprovedCalls:1});expect((await planAugmentation(cfg,ds,'two/model',cache,tok)).calls).toBe(1);expect((await planAugmentation({...cfg,instruction:'New instruction'},ds,'one/model',cache,tok)).calls).toBe(1);});
 it('labels demo results and performs no model calls',async()=>{const config={...cfg,kind:'judgeScore' as const},ds=fresh(['text'],[[string('This passage contains useful information for a reader.')]]);const result=await runAugmentation(config,ds,'demo',{},tok,p=>Promise.resolve(demoAugmentation(config,p.user.split('\n').slice(1).join('\n'))),{maxApprovedCalls:1});expect(result.notes.synthetic).toContain('Demonstration only');expect(result.dataset.records[0].values[2].t).toBe('string');expect(String((result.dataset.records[0].values[2] as {v:string}).v)).toContain('not an LLM');});
});
describe('honest profiles and reports',()=>{
 it('preserves large integer extrema and computes their mean without floating-point rounding',()=>{const ds=fresh(['number'],[[integer('9223372036854775806')],[integer('9223372036854775807')]]);expect(profileColumn(ds,'number',tok).numeric).toMatchObject({min:'9223372036854775806',max:'9223372036854775807',mean:'9223372036854775806.500000'});});
 it('labels deterministic token/language samples and escapes user column names in reports',()=>{const ds=fresh(['text | <script>'],Array.from({length:2100},()=>[string('hello world')]));const card=datasetCard(ds,[],tok,'2026-09-23T00:00:00Z');expect(card.columns[0].tokens).toMatchObject({sampleRows:2000,sampled:true,estimatedTotal:4200});expect(card.languageSampleRows).toBe(500);const markdown=cardMarkdown(card);expect(markdown).toContain('Estimated total: 4200');expect(markdown).not.toContain('<script>');expect(markdown).toContain('text \\| &lt;script&gt;');});
 it('uses nonoverlapping histogram buckets and typed distinctness',()=>{const stats=tokenStats([0,63,64,127,128,8192])!;expect(stats.histogram).toEqual([{label:'0–63',count:2},{label:'64–127',count:2},{label:'128–255',count:1},{label:'8192+',count:1}]);expect(profileColumn(fresh(['x'],[[integer(1)],[string('1')]]),'x',tok).uniqueCount).toBe(2);});
 it('tracks modified cells, added rows/columns and removed identities by stable ID',()=>{const before=fresh(['text'],[[string('old')],[string('gone')]]),after={columns:['text','extra'],records:[{id:0,values:[string('new'),integer(1)]},{id:2,values:[string('added'),integer(2)]}]};expect(datasetDiff(before,after)).toMatchObject({droppedIDs:[1],addedColumns:['extra'],rows:{'0':{kind:'modified',columns:['text']},'2':{kind:'added'}}});});
 it('exports binary cells without dropping any bytes and detects a spaced IBAN before uppercase prose',()=>{const ds=fresh(['payload'],[[{t:'blob',v:'AP8BAg=='}]]);expect(rawJSONL(ds)).toContain('"$binary":"AP8BAg=="');expect(detectPII('DE89 3704 0044 0532 0130 00 TEST',['iban'])[0]?.text).toBe('DE89 3704 0044 0532 0130 00');});
});
