import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fresh, integer, string, NIL, validateDataset, display } from '../src/model';
import { parseLossless, stringifyLossless } from '../src/lossless-json';
import { importCSV, importJSON, importText, importBytes, rawJSONL, rawCSV, markdownSections } from '../src/importers';
import { normalize, aggressive, decodeEntities, decodeBytes } from '../src/normalize';
import { parseInteger, parseDouble, parseDate, inferType, coerce } from '../src/types';
describe('source and typed data integrity', () => {
  it('preserves exact signed 64-bit, larger integers, decimal literals and negative zero through JSONL', () => { const raw = '{"id":9223372036854775807,"negative":-9223372036854775808,"larger":18446744073709551615,"money":123456789.000000001,"zero":-0,"tiny":1e-999}'; const ds = importJSON(raw, 'x.json').dataset; expect(ds.records[0].values[ds.columns.indexOf('id')]).toEqual(integer('9223372036854775807')); expect(parseLossless(rawJSONL(ds).trim())).toEqual(parseLossless(raw)); expect(rawJSONL(ds)).toContain('123456789.000000001'); expect(() => integer(9223372036854775807)).toThrow('Unsafe'); });
  it('rejects duplicate keys, malformed JSON and excessive nesting', () => { for (const s of ['{"x":1,"x":2}', '{"x":01}', '[1,]', 'true false', '"unclosed', '['.repeat(66) + '0' + ']'.repeat(66)]) expect(() => parseLossless(s)).toThrow(); });
  it('keeps prototype-shaped keys as data and refuses flattening collisions', () => { const raw = '{"__proto__":{"text":"data"},"constructor":"literal"}'; expect(stringifyLossless(parseLossless(raw))).toBe(raw); expect(() => importJSON('{"a.b":1,"a":{"b":2}}','x.json')).toThrow('collision'); expect(({} as Record<string, unknown>).text).toBeUndefined(); });
  it('quarantines invalid JSONL with complete source and line numbers', () => { const r = importJSON('{"x":1}\n{broken}\n{"x":2,"x":3}\n{"x":9223372036854775807}', 'x.jsonl', { format:'jsonl' }); expect(r.dataset.records).toHaveLength(2); expect(r.rejected).toHaveLength(2); expect(r.rejected[0]).toMatchObject({row:2,original:'{broken}'}); });
  it('rejects ambiguous wrapped arrays and honors an explicit path', () => { const t = '{"a":[{"x":1}],"b":[{"x":2}]}'; expect(() => importJSON(t,'x.json')).toThrow('Multiple'); expect(importJSON(t,'x.json',{jsonPath:['b']}).dataset.records[0].values[0]).toEqual(integer(2)); });
  it('retains nested arrays without lossy joining', () => { const r = importJSON('[{"tags":["a; b","c"],"profile":{"country":"DE"}}]', 'x.json'); expect(r.dataset.columns).toEqual(['profile.country','tags']); expect(display(r.dataset.records[0].values[1])).toBe('["a; b","c"]'); });
  it('validates row identities, widths, names and finite values', () => { expect(() => fresh(['a','a'], [[NIL,NIL]])).toThrow('distinct'); expect(() => validateDataset({columns:['a'],records:[{id:1,values:[NIL]},{id:1,values:[NIL]}]})).toThrow('identity'); expect(() => fresh(['a'],[[{t:'double',v:Infinity}]])).toThrow('Non-finite'); expect(() => fresh(['a'],[[NIL,NIL]])).toThrow('width'); });
});
describe('CSV, text and encoding', () => {
  it('imports the original fictional support-ticket fixture', () => { const r=importCSV(readFileSync('content/sample-support-tickets.csv','utf8'),'sample.csv'); expect(r.dataset.records).toHaveLength(10);expect(r.dataset.columns).toHaveLength(5);expect(rawJSONL(r.dataset)).toContain('导出功能'); });
  it('reads quoted newlines, escaped quotes, BOM and uneven rows without removing fields', () => { const r=importCSV('\ufeffName,Text\r\nGrüße,"a\r\nb ""c"""\r\nshort\r\n','fixture.csv',{header:'yes'}); expect(r.dataset.records).toHaveLength(2);expect(display(r.dataset.records[0].values[1])).toBe('a\r\nb "c"');expect(r.dataset.records[1].values[1]).toEqual(NIL);expect(r.details.raggedRows).toBe('1'); });
  it('detects semicolons outside multiline quoted cells and supports explicit no-header', () => { const r=importCSV('title;body\nA;"line one,\nline two"\nB;C','x.csv');expect(r.details.delimiter).toBe(';');expect(importCSV('1,2\n3,4','x.csv',{header:'no'}).dataset.records).toHaveLength(2); });
  it('reserves natural suffixes when repairing duplicate column names', () => { expect(importCSV('a,a,a_2,A\n1,2,3,4','x.csv',{header:'yes'}).dataset.columns).toEqual(['a','a_3','a_2','A_4']); });
  it('rejects malformed CSV instead of treating it as successful partial input', () => { for(const s of ['a,b\n"unclosed','a,b\n"x"after,y','a,b\na"b,c']) expect(()=>importCSV(s,'x.csv',{delimiter:',',header:'yes'})).toThrow(); });
  it('distinguishes spreadsheet-safe escaping from exact raw export', () => { const ds=fresh(['x'],[[string('=1+1')],[string('\t@SUM(A1)')],[string('Grüße, "日本語"\nline')]]); const safe=rawCSV(ds); expect(safe.escapedCells).toBe(2);expect(rawJSONL(ds)).toContain('=1+1'); const exact=importCSV(rawCSV(ds,false).text,'x.csv',{header:'yes'});expect(exact.dataset.records).toEqual(ds.records); });
  it('decodes strict BOM encodings and reports fallback', () => { expect(decodeBytes(Uint8Array.from([0xff,0xfe,0x47,0,0xfc,0]))).toMatchObject({text:'Gü',encoding:'UTF-16 LE with BOM'});expect(()=>decodeBytes(Uint8Array.from([0xff,0xfe,0x47]))).toThrow();expect(decodeBytes(Uint8Array.from([0x93,0x48,0x69,0x94]))).toMatchObject({text:'“Hi”',encoding:'Windows-1252 (fallback)'});expect(importBytes(new TextEncoder().encode('x\nü'),'x.csv',{header:'yes'}).details.encoding).toBe('UTF-8'); });
  it('handles Markdown fences by delimiter and opening length', () => { const sections=markdownSections('# Guide\nIntro\n````py\n# code\n```\n# still code\n````\n## Install\nRun.');expect(sections.map(s=>s.heading)).toEqual(['Guide','Install']);expect(sections[0].body).toContain('# still code');expect(importText('# A\nBody','x.md',{format:'markdown'}).dataset.columns).toContain('heading'); });
  it('normalizes in original fixed order and decodes entities once', () => { expect(normalize('“Smart” — quotes&hellip; <b>bold</b>   spaces!!!!',aggressive)).toBe('"Smart" - quotes... bold spaces!');expect(normalize('  a\u200bb\r\nc\x07  ')).toBe('ab\nc');expect(decodeEntities('&amp;lt; &#x1F680; &#xD800;')).toBe('&lt; 🚀 &#xD800;'); });
});
describe('explicit coercion', () => {
  it('rejects malformed grouping, overflow and nonfinite numbers',()=>{expect(parseInteger('9,223,372,036,854,775,807')).toBe(9223372036854775807n);expect(parseInteger('1234,567')).toBeNull();expect(parseInteger('9223372036854775808')).toBeNull();expect(parseDouble('1.234,56')).toBe(1234.56);expect(parseDouble('1,234.56')).toBe(1234.56);expect(parseDouble('12,34,56')).toBeNull();expect(parseDouble('25%')).toBe(.25);expect(parseDouble('1e999')).toBeNull();});
  it('validates calendar and clock fields and discloses deterministic date conventions',()=>{expect(parseDate('15.01.2024')).toBe('2024-01-15T00:00:00.000Z');expect(parseDate('01/02/2024')).toBe('2024-01-02T00:00:00.000Z');expect(parseDate('01.02.2024')).toBe('2024-02-01T00:00:00.000Z');expect(parseDate('2024-02-29T12:30:00+02:00')).toBe('2024-02-29T10:30:00.000Z');for(const s of ['2023-02-29','2024-02-30','2024-01-01 25:00:00','2024-01-01T10:99:00Z'])expect(parseDate(s)).toBeNull();});
  it('infers strings using original threshold and preserves exact integers on coercion',()=>{expect(inferType([string('1'),string('2'),string('N/A')])).toBe('int');expect(coerce(string('9223372036854775807'),'int')).toEqual(integer('9223372036854775807'));expect(coerce(string('bad'),'int')).toEqual(NIL);expect(coerce(string('  NA  '),'string')).toEqual(string('  NA  '));});
});
