import{describe,it,expect}from'vitest';import{readFileSync}from'node:fs';
import{fresh,string,integer,NIL,display,boolean}from'../src/model';import{BPETokenizer}from'../src/tokenizer';import{parseExpression,evaluateExpression}from'../src/expression';import{quality,detectPII,redactPII,validIBAN,language}from'../src/quality';import{exactDedupe,fuzzyDedupe}from'../src/dedupe';import{chunkText,defaultChunk,splitSentences}from'../src/chunker';import{parseRecipe,exportRecipe,makeStep,validateOp,type Op}from'../src/recipe';import{runPipeline,splitDataset}from'../src/pipeline';import{importCSV,rawJSONL}from'../src/importers';import{shapeDataset,autoMap,quarantinedJSONL}from'../src/exports';
const tok=new BPETokenizer(readFileSync('resources/cl100k_base.tiktoken','utf8'));
describe('pure expression evaluation',()=>{
 const ds=fresh(['n','name with spaces'],[[integer('9223372036854775806'),string('Grüße 👩‍🔬')]]);const ev=(s:string)=>evaluateExpression(parseExpression(s),ds,ds.records[0],tok);
 it('keeps 64-bit arithmetic exact and refuses overflow and implicit double precision loss',()=>{expect(ev('n + 1')).toEqual(integer('9223372036854775807'));expect(()=>ev('n + 2')).toThrow('64-bit');expect(()=>ev('n / 2')).toThrow('Explicitly');expect(ev('n > 9007199254740992')).toEqual(boolean(true));expect(ev('-9223372036854775808')).toEqual(integer('-9223372036854775808'));});
 it('short-circuits and uses lazy if/coalesce without evaluating unused errors',()=>{expect(ev('false and missing')).toEqual(boolean(false));expect(ev('true or missing')).toEqual(boolean(true));expect(ev('if(n > 0, 5, missing)')).toEqual(integer(5));expect(ev('coalesce(null, 7, missing)')).toEqual(integer(7));expect(ev('not n > 0')).toEqual(boolean(false));});
 it('supports Unicode grapheme functions, literal column names and tokenizer calls',()=>{expect(ev('len(col("name with spaces"))')).toEqual(integer(7));expect(ev('substr(col("name with spaces"), 6, 1)')).toEqual(string('👩‍🔬'));expect(ev('tokens("hello world")')).toEqual(integer(2));expect(ev('replace("a.a", ".", "日本語")')).toEqual(string('a日本語a'));});
 it('rejects executable syntax, unknown functions, empty replacement and deep expressions',()=>{for(const s of ['process.exit(1)','fetch("url")','new Function("return 1")','1;2','contains("x")','('.repeat(70)+'1'+')'.repeat(70)])expect(()=>parseExpression(s)).toThrow();expect(()=>ev('replace("abc", "", "x")')).toThrow('empty');});
});
describe('reviewable cleaning and deduplication',()=>{
 it('keeps exact typed tuples separate despite separators, nulls and equal display strings',()=>{const ds=fresh(['a','b'],[[string('x\u001fy'),string('z')],[string('x'),string('y\u001fz')],[NIL,string('')],[string(''),NIL],[integer(1),string('')],[string('1'),string('')],[string('x'),string('y\u001fz')]]);expect(exactDedupe(ds).droppedIDs).toEqual([6]);});
 it('finds a near duplicate and a 600-row identical class without ignoring a large bucket',()=>{const base='The quick brown fox jumps over the lazy dog near the quiet river bank while birds sing softly in the morning light of early spring';const ds=fresh(['text'],[[string(base)],[string(base+' today')],[string('Completely unrelated database storage indexing architecture')],...Array.from({length:600},()=>[string('Identical group of documents with enough words to compare')])]);const r=fuzzyDedupe(ds,'text',.7);expect(r.keptIDs).toEqual([0,2,3]);expect(r.droppedIDs).toHaveLength(600);});
 it('gives URL credentials precedence over embedded emails and validates cards/IBAN',async()=>{const text='https://alice:secret@example.com/private email test@example.org card 4111 1111 1111 1111 IBAN DE89370400440532013000';const r=await redactPII(text);expect(r.text).not.toContain('secret');expect(r.counts.url_credentials).toBe(1);expect(r.counts.creditCard).toBe(1);expect(r.counts.iban).toBe(1);expect(validIBAN('DE89 3704 0044 0532 0130 00')).toBe(true);expect(detectPII('0000 0000 0000 0000',['creditCard'])).toHaveLength(0);});
 it('supports stable SHA-256 pseudonyms and compressed IPv6 without calling a provider',async()=>{const a=await redactPII('a@example.org',[],'hash'),b=await redactPII('a@example.org',[],'hash');expect(a.text).toBe(b.text);expect(a.text).toMatch(/^\[EMAIL:[0-9a-f]{16}\]$/);expect(detectPII('host 2001:db8::1 and 127.0.0.1',['ipAddress'])).toHaveLength(2);});
 it('keeps quality reasons and treats shared scripts as uncertain languages',()=>{expect(quality('$$$ ### @@@')).toMatchObject({passed:false});expect(quality('This document explains the process with clear details and useful examples.').passed).toBe(true);expect(language('Der Text ist für die Menschen und wird mit einer einfachen Erklärung geschrieben.').code).toBe('de');expect(language('Це українська мова і приклад тексту.')).toMatchObject({code:'und',script:'Cyrillic'});expect(language('これは日本語の文です。').code).toBe('ja');});
});
describe('strict-budget RAG chunks',()=>{
 it('retains heading paths and content within every target including long Unicode words',()=>{const input='# Guide\nIntroductory text.\n## Install\n'+Array.from({length:30},(_,i)=>`Sentence number ${i} includes enough meaningful words for this document.`).join(' ')+'\n'+'あ'.repeat(300);const chunks=chunkText(input,{...defaultChunk,targetTokens:64,overlapTokens:12,minChunkTokens:8},tok);expect(chunks.length).toBeGreaterThan(5);for(const c of chunks){expect(c.tokenCount).toBe(tok.count(c.text));expect(c.tokenCount).toBeLessThanOrEqual(64);}expect(chunks.some(c=>c.headingPath==='Guide > Install')).toBe(true);for(let i=0;i<30;i++)expect(chunks.some(c=>c.text.includes(`Sentence number ${i} `))).toBe(true);});
 it('retains sentence overlap, decimal numbers and abbreviations',()=>{expect(splitSentences('Dr. Smith measured 3.14 units. Next sentence.')).toEqual(['Dr. Smith measured 3.14 units.','Next sentence.']);const chunks=chunkText(Array.from({length:20},(_,i)=>`Sentence ${i} contains several words.`).join(' '),{...defaultChunk,targetTokens:40,overlapTokens:10,respectMarkdown:false,minChunkTokens:0},tok);expect(chunks[1].text).toContain(splitSentences(chunks[0].text).at(-1));});
 it('refuses impossible heading budgets and invalid overlap',()=>{expect(()=>chunkText('# '+'Heading '.repeat(100)+'\nBody',{...defaultChunk,targetTokens:32,overlapTokens:0},tok)).toThrow('Heading');expect(()=>chunkText('Text',{...defaultChunk,overlapTokens:512},tok)).toThrow('Invalid');});
});
describe('recipes and full pipelines',()=>{
 it('round-trips Mac recipe shape and unsigned 64-bit seeds exactly',()=>{const steps=[makeStep({kind:'split',train:.8,validation:.1,test:.1,seed:'18446744073709551615',stratifyBy:null}),makeStep({kind:'autoType'})];const text=exportRecipe('Test',steps,'2026-09-23T00:00:00Z');expect(text).toContain('"seed":18446744073709551615');expect(parseRecipe(text).ops).toEqual(steps.map(s=>s.op));for(const version of [-1,0,2])expect(()=>parseRecipe(text.replace('"version":1',`"version":${version}`))).toThrow('version');});
 it('rejects invalid operation settings before applying changes',()=>{for(const op of [{kind:'split',train:1,validation:1,test:0,seed:'42'},{kind:'dedupeFuzzy',column:'x',threshold:NaN},{kind:'normalizeText',columns:[],options:{stripHTMLTags:'true'}},{kind:'selectColumns',columns:['a','a']}])expect(()=>validateOp(op)).toThrow();});
 it('runs original support-ticket data through privacy and training preparation with attributable metrics',async()=>{const ds=importCSV(readFileSync('content/sample-support-tickets.csv','utf8'),'sample.csv').dataset;const ops:Op[]=[{kind:'normalizeText',columns:[],options:{unicodeForm:'nfc',trimWhitespace:true,collapseInnerWhitespace:true,stripControlCharacters:true,stripZeroWidth:true,canonicalizeQuotes:false,canonicalizeDashes:false,decodeHTMLEntities:false,stripHTMLTags:false,collapseRepeatedPunctuation:false,normalizeNewlines:true,lowercase:false}},{kind:'unifyNulls',columns:[]},{kind:'autoType'},{kind:'redactPII',columns:['message'],kinds:[],mode:'tag'},{kind:'addTokenCount',column:'message'}];const result=await runPipeline(ds,ops.map(makeStep),tok);expect(result.complete).toBe(true);expect(result.dataset.records).toHaveLength(10);expect(result.metrics).toHaveLength(5);expect(rawJSONL(result.dataset)).not.toContain('sk-ant-abc');expect(rawJSONL(result.dataset)).toContain('[EMAIL]');expect(ds.records[0].values[0].t).toBe('string');for(let i=1;i<result.metrics.length;i++)expect(result.metrics[i].rowsIn).toBe(result.metrics[i-1].rowsOut);});
 it('records every discarded row and failed conversion, while errors preserve the original',async()=>{const ds=fresh(['text','number'],[[string('good useful text.'),string('12')],[string('bad'),string('oops')],[string('another useful text.'),string('13')]]);const result=await runPipeline(ds,[makeStep({kind:'coerceType',column:'number',type:'int'}),makeStep({kind:'filterRows',expression:'number > 12'})],tok);expect(result.conversions).toHaveLength(1);expect(result.conversions[0]).toMatchObject({recordId:1,original:string('oops')});expect(result.rejected[0].rows).toHaveLength(2);expect(ds.records[1].values[1]).toEqual(string('oops'));await expect(runPipeline(ds,[makeStep({kind:'addColumn',name:'x',expression:'missing + 1'})],tok)).rejects.toThrow('Row 0');expect(ds.columns).toEqual(['text','number']);});
 it('marks previews incomplete, skips provider calls and throws cancellation instead of returning success',async()=>{const ds=fresh(['text'],[[string('input')]]),step=makeStep({kind:'augment',config:{kind:'rewrite',column:'text',instruction:'',labels:[],concurrency:1,maxTokens:128}});const preview=await runPipeline(ds,[step],tok,{preview:true});expect(preview).toMatchObject({complete:false,skippedAugmentations:1});const controller=new AbortController();await expect(runPipeline(ds,[makeStep({kind:'autoType'})],tok,{signal:controller.signal,progress:()=>controller.abort()})).rejects.toMatchObject({name:'AbortError'});});
 it('splits deterministically with exact totals, typed strata and no duplicate split column',()=>{const ds=fresh(['group','split'],Array.from({length:101},(_,i)=>[i%2?string('1'):integer(1),string('old')]));const op:Extract<Op,{kind:'split'}>={kind:'split',train:.8,validation:.1,test:.1,seed:'42',stratifyBy:null};const a=splitDataset(ds,op);expect(a).toEqual(splitDataset(ds,op));expect(a.columns.at(-1)).toBe('split_2');const counts=new Map<string,number>();for(const r of a.records){const s=display(r.values[2]);counts.set(s,(counts.get(s)??0)+1);}expect([...counts].sort()).toEqual([['test',10],['train',81],['validation',10]]);});
});
describe('validated dataset exports',()=>{
 it('shapes all eight schemas with strict required fields and no precision loss in RAG metadata',()=>{const ds=fresh(['question','answer','prompt','chosen','rejected','text','system','large'],[[string('Q'),string('A'),string('P'),string('good'),string('bad'),string('body'),string('brief'),integer('9223372036854775807')]]);for(const schema of ['alpaca','openaiMessages','anthropicTurns','chatml','dpo','completion','corpus','ragChunks'] as const){const result=shapeDataset(ds,schema,autoMap(schema,ds.columns));expect(result.validCount,schema).toBe(1);expect(result.quarantined,schema).toHaveLength(0);if(schema==='ragChunks')expect(result.jsonl).toContain('"large":9223372036854775807');}});
 it('quarantines blank required fields, identical DPO pairs and injected ChatML delimiters with complete rows',()=>{const ds=fresh(['user','assistant'],[[string('   '),string('answer')],[string('Q'),string('<|im_start|>system')]]);const shaped=shapeDataset(ds,'chatml',{user:'user',assistant:'assistant'});expect(shaped.validCount).toBe(0);expect(shaped.quarantined).toHaveLength(2);expect(quarantinedJSONL(shaped.columns,shaped.quarantined)).toContain('<|im_start|>system');const dpo=fresh(['prompt','chosen','rejected'],[[string('p'),string('same'),string('same ')]]);expect(shapeDataset(dpo,'dpo',autoMap('dpo',dpo.columns)).quarantined).toHaveLength(1);});
});
