const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{DatabaseSync}=require('node:sqlite'),reader=require('../electron/sqlite.cjs');
(async()=>{await fs.mkdir('release',{recursive:true});const root=path.resolve('release'),folder=await fs.mkdtemp(path.join(root,'sqlite-qa-'));let count=0;const check=fn=>{fn();count++;},digest=async file=>crypto.createHash('sha256').update(await fs.readFile(file)).digest('hex');const fixture=path.join(folder,'Grüße 日本語.sqlite');let writer;
try{
 writer=new DatabaseSync(fixture);writer.exec('PRAGMA journal_mode=WAL; PRAGMA wal_autocheckpoint=0; CREATE TABLE items (id INTEGER,text TEXT,payload BLOB,score REAL);');const insert=writer.prepare('INSERT INTO items VALUES (?,?,?,?)');insert.run(9223372036854775807n,'Grüße 日本語\u0000end',Buffer.from([0,255,1,2]),1.25);insert.run(-9223372036854775808n,'\ufeffpreserved',null,null);writer.exec('CREATE VIEW item_view AS SELECT * FROM items;');
 const before=await Promise.all([digest(fixture),digest(fixture+'-wal'),digest(fixture+'-shm')]);const list=await reader.listTables(fixture);check(()=>assert.deepEqual(list.tables.map(t=>t.name),['item_view','items']));const result=await reader.importTable(fixture,'items');check(()=>assert.equal(result.dataset.records.length,2));check(()=>assert.deepEqual(result.dataset.records[0].values[0],{t:'int',v:'9223372036854775807'}));check(()=>assert.equal(result.dataset.records[1].values[0].v,'-9223372036854775808'));check(()=>assert.equal(result.dataset.records[0].values[1].v,'Grüße 日本語\u0000end'));check(()=>assert.equal(result.dataset.records[1].values[1].v,'\ufeffpreserved'));check(()=>assert.deepEqual(result.dataset.records[0].values[2],{t:'blob',v:'AP8BAg=='}));check(()=>assert.deepEqual(result.dataset.records[1].values[2],{t:'null'}));check(()=>assert.equal(result.dataset.records[0].values[3].v,1.25));const view=await reader.importTable(fixture,'item_view');check(()=>assert.deepEqual(view.dataset,result.dataset));
 const after=await Promise.all([digest(fixture),digest(fixture+'-wal'),digest(fixture+'-shm')]);check(()=>assert.deepEqual(after,before));await assert.rejects(()=>reader.importTable(fixture,'items";DROP TABLE items;--'),/no longer exists/);count++;
 writer.exec("CREATE TABLE invalid_text(text TEXT); INSERT INTO invalid_text VALUES(CAST(x'fffe' AS TEXT));");await assert.rejects(()=>reader.importTable(fixture,'invalid_text'),/encoded|encoding|valid/i);count++;
 writer.exec('CREATE VIEW too_many AS WITH RECURSIVE x(n) AS (VALUES(1) UNION ALL SELECT n+1 FROM x WHERE n<50001) SELECT n FROM x;');await assert.rejects(()=>reader.importTable(fixture,'too_many'),/limit/);count++;
 writer.close();writer=null;
 const utf16=path.join(folder,'UTF16.sqlite'),u=new DatabaseSync(utf16);u.exec("PRAGMA encoding='UTF-16le'; CREATE TABLE texts (value TEXT);");u.prepare('INSERT INTO texts VALUES (?)').run('Grüße 日本語');u.close();const imported=await reader.importTable(utf16,'texts');check(()=>assert.equal(imported.dataset.records[0].values[0].v,'Grüße 日本語'));
 for(const raw of ['\\\\server\\share\\x.sqlite','C:\\x.sqlite:stream','relative.sqlite','C:\\folder.\\x.sqlite']){check(()=>assert.throws(()=>reader.localPath(raw)));}
 const link=path.join(folder,'junction'),outside=path.join(folder,'actual');await fs.mkdir(outside);await fs.copyFile(utf16,path.join(outside,'data.sqlite'));await fs.symlink(outside,link,'junction');await assert.rejects(()=>reader.importTable(path.join(link,'data.sqlite'),'texts'),/junction/);count++;await fs.unlink(link);
 const report={passed:true,checks:count,node:process.versions.node,electron:process.versions.electron??null,sqlite:list.sqlite,fixtures:'Owned synthetic databases only; source DB/WAL/SHM checksum preservation verified.',nativeGUI:false};await fs.writeFile('release/native-sqlite-verification.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{writer?.close();const resolved=path.resolve(folder);if(path.dirname(resolved)!==root||!path.basename(resolved).startsWith('sqlite-qa-'))throw Error('Unsafe fixture cleanup target.');await fs.rm(resolved,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
