export type ProviderConfig={provider:string;endpoint:string;model:string};export type ProviderStatus={native:boolean;enabled:boolean;saved:boolean;credentialStored:boolean;config:ProviderConfig|null;presets:Record<string,[string,string,string,string]>};
declare global{interface Window{desktop?:{invoke:(command:string,args?:unknown)=>Promise<any>;onProgress:(callback:(text:string)=>void)=>()=>void;onReview:(callback:(review:any)=>void)=>()=>void}}}
type Pending={resolve:(value:any)=>void;reject:(error:Error)=>void};
export class WorkspaceAPI{
 private worker:Worker|null=null;private pending=new Map<number,Pending>();private next=0;private ready!:Promise<void>;private readyResolve!:()=>void;private readyReject!:(error:Error)=>void;onProgress:(text:string)=>void=()=>{};readonly native=!!window.desktop;
 onReview:(review:any)=>void=()=>{};
 constructor(){if(this.native){window.desktop!.onProgress(text=>this.onProgress(text));window.desktop!.onReview(review=>this.onReview(review));}else this.startWorker();}
 private startWorker(){this.ready=new Promise((resolve,reject)=>{this.readyResolve=resolve;this.readyReject=reject;});this.worker=new Worker(new URL('./browser-worker.ts',import.meta.url),{type:'module'});this.worker.onmessage=({data})=>{if(data.event==='ready'){this.readyResolve();return;}if(data.event==='initialization-error'){this.readyReject(Error(data.error));return;}if(data.event==='progress'){this.onProgress(data.text);return;}const entry=this.pending.get(data.id);if(!entry)return;this.pending.delete(data.id);data.error?entry.reject(Error(data.error)):entry.resolve(data.value);};this.worker.onerror=()=>{const error=Error('Workspace worker failed. The previous saved workspace is available for recovery.');this.readyReject(error);for(const p of this.pending.values())p.reject(error);this.pending.clear();};}
 async invoke(command:string,args:unknown={}):Promise<any>{if(this.native)return window.desktop!.invoke(command,args);if(command==='provider-status')return{native:false,enabled:false,saved:false,credentialStored:false,config:null,presets:{}} satisfies ProviderStatus;if(command==='cancel'){this.worker?.terminate();for(const p of this.pending.values())p.reject(Error('Run cancelled. Completed saved responses remain available.'));this.pending.clear();this.startWorker();await this.ready;return this.invoke('overview');}await this.ready;return new Promise((resolve,reject)=>{const id=++this.next;this.pending.set(id,{resolve,reject});this.worker!.postMessage({id,command,args});});}
}
