import{BPETokenizer}from'./tokenizer';import{AlembicEngine}from'./engine';import{emptyWorkspace,validateWorkspace,type Workspace}from'./workspace';import{runAugmentation,demoAugmentation,planAugmentation}from'./augmentation';
const scope=self as unknown as{postMessage:(message:unknown)=>void;onmessage:((event:MessageEvent)=>void)|null};
let db:IDBDatabase,engine:AlembicEngine,storageError='';
const open=new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('alembic-windows-browser-preview',1);request.onupgradeneeded=()=>request.result.createObjectStore('snapshots');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
function read(key:string):Promise<unknown>{return new Promise((resolve,reject)=>{const tx=db.transaction('snapshots','readonly'),request=tx.objectStore('snapshots').get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
function save(state:Workspace):Promise<void>{return new Promise((resolve,reject)=>{const tx=db.transaction('snapshots','readwrite'),store=tx.objectStore('snapshots'),previous=store.get('current');previous.onsuccess=()=>{if(previous.result){try{store.put(validateWorkspace(previous.result),'previous');}catch{store.put(previous.result,'before-recovery');}}store.put(state,'current');};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error??Error('Browser preview save failed.'));tx.onabort=()=>reject(tx.error??Error('Browser preview save aborted.'));});}
async function recover(){const previous=await read('previous');if(!previous)throw Error('No previous browser save is available.');const checked=validateWorkspace(previous);await new Promise<void>((resolve,reject)=>{const tx=db.transaction('snapshots','readwrite'),store=tx.objectStore('snapshots'),current=store.get('current');current.onsuccess=()=>{store.put(current.result,'before-recovery');store.put(checked,'current');};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});engine.state=checked;storageError='';await engine.refreshPreview();return engine.overview();}
async function initialize(){db=await open;const response=await fetch('/cl100k_base.tiktoken');if(!response.ok)throw Error('Bundled tokenizer failed to load.');const tokenizer=new BPETokenizer(await response.text()),saved=await read('current');let initial=emptyWorkspace();try{if(saved)initial=validateWorkspace(saved);}catch(e){storageError='The current browser snapshot could not be read: '+(e as Error).message;}engine=new AlembicEngine(tokenizer,{save,progress:text=>scope.postMessage({event:'progress',text}),augment:async(config,dataset)=>{const plan=await planAugmentation(config,dataset,'demo',engine.state.cache,tokenizer);return runAugmentation(config,dataset,'demo',engine.state.cache,tokenizer,p=>Promise.resolve(demoAugmentation(config,p.user.slice(p.user.indexOf('\n')+1))),{maxApprovedCalls:plan.calls,checkpoint:(key,values)=>engine.checkpoint(key,values),progress:(done,total)=>scope.postMessage({event:'progress',text:`Offline demonstration: ${done}/${total} rows`})});}},initial);await engine.refreshPreview();scope.postMessage({event:'ready'});}
const ready=initialize();ready.catch(e=>scope.postMessage({event:'initialization-error',error:e.message}));
scope.onmessage=async({data})=>{const{id,command,args}=data??{};try{await ready;if(command==='recover'){if(engine.busy)throw Error('An operation is running.');scope.postMessage({id,value:await recover()});return;}if(storageError&&!['overview','backup','new'].includes(command))throw Error(storageError+' Restore a saved snapshot before continuing.');const value=await engine.command(command,args);if(command==='backup'||command==='new')storageError='';scope.postMessage({id,value:command==='overview'?{...value,storageError}:value});}catch(e){scope.postMessage({id,error:(e as Error).message});}};
