import {type Dataset,type DataRow,display,requireColumn} from './model';
import {type JSONValue,cellJSON,stringifyLossless} from './lossless-json';
export const schemas={alpaca:{name:'Instruction (Alpaca)',required:['instruction','output'],optional:['input']},openaiMessages:{name:'Chat (OpenAI messages)',required:['user','assistant'],optional:['system']},anthropicTurns:{name:'Chat (Anthropic turns)',required:['user','assistant'],optional:['system']},chatml:{name:'ChatML (rendered)',required:['user','assistant'],optional:['system']},dpo:{name:'Preference pairs (DPO)',required:['prompt','chosen','rejected'],optional:[]},completion:{name:'Prompt → completion',required:['prompt','completion'],optional:[]},corpus:{name:'Raw corpus',required:['text'],optional:[]},ragChunks:{name:'RAG chunks',required:['text'],optional:['source','heading']}} as const;
export type Schema=keyof typeof schemas;export type Mapping=Record<string,string>;
const synonyms:Record<string,string[]>={instruction:['instruction','question','prompt','query','task','q'],input:['input','context','passage'],output:['output','answer','response','completion','a'],system:['system','system_prompt'],user:['user','question','prompt','instruction','human','q','input'],assistant:['assistant','answer','response','output','completion','a','bot'],prompt:['prompt','question','instruction','query','input'],chosen:['chosen','preferred','good','winner'],rejected:['rejected','dispreferred','bad','loser'],completion:['completion','output','answer','response','text'],text:['text','content','body','document','passage'],source:['source','file','url','origin','doc'],heading:['heading','title','section','heading_path']};
export function autoMap(schema:Schema,columns:string[]):Mapping{const map:Mapping=Object.create(null);for(const field of [...schemas[schema].required,...schemas[schema].optional])for(const alias of synonyms[field]){const hits=columns.filter(c=>c.toLowerCase()===alias);if(hits.length===1){map[field]=hits[0];break;}}return map;}
export type ShapeResult={jsonl:string;validCount:number;quarantined:{record:DataRow;reason:string}[];columns:string[]};
export function shapeDataset(ds:Dataset,schema:Schema,mapping:Mapping):ShapeResult{if(!Object.hasOwn(schemas,schema))throw Error('Unknown export schema.');const spec=schemas[schema],fields=[...spec.required,...spec.optional],indexes=new Map<string,number>();for(const field of fields)if(mapping[field])indexes.set(field,requireColumn(ds,mapping[field]));const lines:string[]=[],quarantined:ShapeResult['quarantined']=[];
  for(const row of ds.records){const get=(field:string)=>{const idx=indexes.get(field);return idx===undefined?'':display(row.values[idx]);},missing=spec.required.filter(f=>!get(f).trim());if(missing.length){quarantined.push({record:row,reason:'Missing required fields: '+missing.join(', ')});continue;}let obj:Record<string,JSONValue>=Object.create(null);
    switch(schema){case'alpaca':obj={instruction:get('instruction'),input:get('input'),output:get('output')};break;case'openaiMessages':obj={messages:[...(get('system').trim()?[{role:'system',content:get('system')}]:[]),{role:'user',content:get('user')},{role:'assistant',content:get('assistant')}]};break;case'anthropicTurns':obj={...(get('system').trim()?{system:get('system')}:{}),messages:[{role:'user',content:get('user')},{role:'assistant',content:get('assistant')}]};break;case'chatml':if(fields.some(f=>/<\|im_(?:start|end)\|>/.test(get(f)))){quarantined.push({record:row,reason:'ChatML control delimiter occurs in field content.'});continue;}obj={text:(get('system')?`<|im_start|>system\n${get('system')}<|im_end|>\n`:'')+`<|im_start|>user\n${get('user')}<|im_end|>\n<|im_start|>assistant\n${get('assistant')}<|im_end|>`};break;case'dpo':if(get('chosen').trim()===get('rejected').trim()){quarantined.push({record:row,reason:'Chosen and rejected responses are identical.'});continue;}obj={prompt:get('prompt'),chosen:get('chosen'),rejected:get('rejected')};break;case'completion':obj={prompt:get('prompt'),completion:get('completion')};break;case'corpus':obj={text:get('text')};break;case'ragChunks':{const metadata:Record<string,JSONValue>=Object.create(null),extra:Record<string,JSONValue>=Object.create(null),mapped=new Set(indexes.values());if(indexes.has('source'))metadata.source=get('source');if(indexes.has('heading'))metadata.heading=get('heading');ds.columns.forEach((c,i)=>{if(!mapped.has(i))extra[c]=cellJSON(row.values[i]);});if(Object.keys(extra).length)metadata.fields=extra;obj={id:row.id,text:get('text'),metadata};break;}}
    lines.push(stringifyLossless(obj));
  }
  return{jsonl:lines.join('\n')+(lines.length?'\n':''),validCount:lines.length,quarantined,columns:ds.columns};
}
export function quarantinedJSONL(columns:string[],rows:{record:DataRow;reason:string}[],metadata:{stepId:string;opName:string}|null=null):string{return rows.map(({record,reason})=>{const data:Record<string,JSONValue>=Object.create(null);columns.forEach((c,i)=>data[c]=cellJSON(record.values[i]));return stringifyLossless({...metadata,recordId:record.id,reason,data});}).join('\n')+(rows.length?'\n':'');}
