import { type Value, type Dataset, type DataRow, NIL, integer, double, string, boolean, display, truthy, numeric, requireColumn, graphemes, limits } from './model';
import type { Tokenizer } from './tokenizer';
import { language } from './quality';
type Token = { type: 'number' | 'string' | 'id' | 'op' | 'end'; text: string; pos: number };
export type Expr = { kind: 'value'; value: Value } | { kind: 'column'; name: string } | { kind: 'unary'; op: string; right: Expr } | { kind: 'binary'; op: string; left: Expr; right: Expr } | { kind: 'call'; name: string; args: Expr[] };
const precedence: Record<string, number> = { or:1,'||':1,and:2,'&&':2,'==':3,'!=':3,'<':4,'>':4,'<=':4,'>=':4,'+':5,'-':5,'*':6,'/':6,'%':6 };
const arities: Record<string,[number,number]> = { len:[1,1],lower:[1,1],upper:[1,1],trim:[1,1],contains:[2,2],starts_with:[2,2],ends_with:[2,2],replace:[3,3],substr:[2,3],concat:[1,50],coalesce:[1,50],col:[1,1],tokens:[1,1],words:[1,1],lang:[1,1],is_null:[1,1],abs:[1,1],round:[1,2],min:[1,50],max:[1,50],if:[3,3] };
function lex(input:string):Token[]{if(input.length>10000)throw Error('Expression exceeds 10,000 characters.');const out:Token[]=[];let pos=0;while(pos<input.length){if(/\s/u.test(input[pos])){pos++;continue;}const start=pos,c=input[pos];if(c==='"'||c==="'"){pos++;let s='',closed=false;while(pos<input.length){const ch=input[pos++];if(ch===c){closed=true;break;}if(ch==='\\'){if(pos===input.length)throw Error('Unclosed expression escape.');const next=input[pos++];s+=next==='n'?'\n':next==='t'?'\t':next==='r'?'\r':next;}else s+=ch;}if(!closed)throw Error('Unclosed expression string.');out.push({type:'string',text:s,pos:start});continue;}const number=input.slice(pos).match(/^(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?/);if(number){pos+=number[0].length;out.push({type:'number',text:number[0],pos:start});continue;}const id=input.slice(pos).match(/^[\p{L}_][\p{L}\p{M}\p{N}_]*/u);if(id){pos+=id[0].length;out.push({type:['and','or','not'].includes(id[0])?'op':'id',text:id[0],pos:start});continue;}const pair=input.slice(pos,pos+2);if(['==','!=','<=','>=','&&','||'].includes(pair)){pos+=2;out.push({type:'op',text:pair,pos:start});continue;}if('()+-*/%,!<>'.includes(c)){pos++;out.push({type:'op',text:c,pos:start});continue;}throw Error(`Unexpected expression character at ${pos+1}.`);}out.push({type:'end',text:'',pos});if(out.length>2000)throw Error('Expression exceeds 2,000 tokens.');return out;}
export function parseExpression(input:string):Expr{const tokens=lex(input);let pos=0,nodes=0;const peek=()=>tokens[pos],take=()=>tokens[pos++];function need(t:string){if(take().text!==t)throw Error(`Expected ${t} at character ${peek()?.pos??input.length}.`);}
  function parse(min=1,depth=0):Expr{if(depth>64||++nodes>2000)throw Error('Expression complexity limit exceeded.');let left:Expr;const t=take();
    if(t.type==='number')left={kind:'value',value:/^\d+$/.test(t.text)?integer(t.text):double(Number(t.text))};
    else if(t.type==='string')left={kind:'value',value:string(t.text)};
    else if(t.text==='not'||t.text==='!'||t.text==='-'){if(t.text==='-'&&peek().type==='number'&&/^\d+$/.test(peek().text)){left={kind:'value',value:integer('-'+take().text)};}else left={kind:'unary',op:t.text,right:parse(t.text==='not'?3:7,depth+1)};}
    else if(t.text==='('){left=parse(1,depth+1);need(')');}
    else if(t.type==='id'){if(['true','false','null'].includes(t.text))left={kind:'value',value:t.text==='null'?NIL:boolean(t.text==='true')};else if(peek().text==='('){take();const args:Expr[]=[];if(peek().text!==')'){while(true){args.push(parse(1,depth+1));if(peek().text!==',')break;take();}}need(')');const arity=arities[t.text];if(!arity)throw Error(`Unknown function: ${t.text}`);if(args.length<arity[0]||args.length>arity[1])throw Error(`Invalid argument count for ${t.text}.`);left={kind:'call',name:t.text,args};}else left={kind:'column',name:t.text};}
    else throw Error(`Expected expression at character ${t.pos+1}.`);
    while((precedence[peek().text]??0)>=min){const op=take().text,right=parse(precedence[op]+1,depth+1);left={kind:'binary',op,left,right};}return left;
  }const expr=parse();if(peek().type!=='end')throw Error(`Unexpected expression input at character ${peek().pos+1}.`);return expr;}
function compare(a:Value,b:Value):number{if(a.t==='null'||b.t==='null')return a.t===b.t?0:a.t==='null'?-1:1;const numericType=(v:Value)=>['int','double','bool'].includes(v.t);if(numericType(a)&&numericType(b)){const val=(v:Value):bigint|number=>v.t==='int'?BigInt(v.v):v.t==='bool'?(v.v?1:0):(v as {t:'double';v:number}).v;const x=val(a),y=val(b);return x<y?-1:x>y?1:0;}const x=display(a),y=display(b);return x<y?-1:x>y?1:0;}
export function evaluateExpression(expr:Expr,ds:Dataset,row:DataRow,tokenizer:Tokenizer):Value{let operations=0;function run(e:Expr,depth=0):Value{if(++operations>5000||depth>128)throw Error('Expression evaluation limit exceeded.');if(e.kind==='value')return e.value;if(e.kind==='column')return row.values[requireColumn(ds,e.name)];if(e.kind==='unary'){const v=run(e.right,depth+1);return e.op==='-'?(v.t==='int'?integer(-BigInt(v.v)):double(-numeric(v))):boolean(!truthy(v));}if(e.kind==='binary'){const a=run(e.left,depth+1);if(e.op==='and'||e.op==='&&')return boolean(truthy(a)&&truthy(run(e.right,depth+1)));if(e.op==='or'||e.op==='||')return boolean(truthy(a)||truthy(run(e.right,depth+1)));const b=run(e.right,depth+1);if(['==','!=','<','>','<=','>='].includes(e.op)){const c=compare(a,b);return boolean(e.op==='=='?c===0:e.op==='!='?c!==0:e.op==='<'?c<0:e.op==='>'?c>0:e.op==='<='?c<=0:c>=0);}if(e.op==='+'&&(a.t==='string'||b.t==='string'))return string(display(a)+display(b));if(a.t==='null'||b.t==='null')return NIL;
    if(a.t==='int'&&b.t==='int'&&e.op!=='/'){const x=BigInt(a.v),y=BigInt(b.v);if(e.op==='%'&&y===0n)return NIL;return integer(e.op==='+'?x+y:e.op==='-'?x-y:e.op==='*'?x*y:x%y);}const x=numeric(a),y=numeric(b);if((e.op==='/'||e.op==='%')&&y===0)return NIL;return double(e.op==='+'?x+y:e.op==='-'?x-y:e.op==='*'?x*y:e.op==='/'?x/y:x%y);
  }
  if(e.name==='if')return run(truthy(run(e.args[0],depth+1))?e.args[1]:e.args[2],depth+1);
  if(e.name==='coalesce'){for(const x of e.args){const v=run(x,depth+1);if(v.t!=='null')return v;}return NIL;}
  const args=e.args.map(a=>run(a,depth+1)),s=(i=0)=>display(args[i]);const index=(i:number)=>{const n=args[i].t==='int'?Number(args[i].v):numeric(args[i]);if(!Number.isSafeInteger(n))throw Error('Expected a safe integer index.');return n;};
  switch(e.name){case'len':return integer(graphemes(s()).length);case'lower':return string(s().toLowerCase());case'upper':return string(s().toUpperCase());case'trim':return string(s().trim());case'contains':return boolean(s().includes(s(1)));case'starts_with':return boolean(s().startsWith(s(1)));case'ends_with':return boolean(s().endsWith(s(1)));case'replace':{const source=s(),find=s(1),replacement=s(2);if(!find)throw Error('Replacement search text cannot be empty.');let count=0,position=0;while((position=source.indexOf(find,position))!==-1){count++;position+=find.length;if(source.length+count*(replacement.length-find.length)>limits.cellChars)throw Error('Replacement output exceeds the cell limit.');}return string(source.split(find).join(replacement));}case'substr':{const start=index(1),length=args.length===3?index(2):undefined;if(start<0||length!==undefined&&length<0)throw Error('Substring indexes must be nonnegative.');return string(graphemes(s()).slice(start,length===undefined?undefined:start+length).join(''));}case'concat':return string(args.map(display).join(''));case'col':return row.values[requireColumn(ds,s())];case'tokens':return integer(tokenizer.count(s()));case'words':return integer(s().trim()?s().trim().split(/\s+/u).length:0);case'lang':return string(language(s()).code);case'is_null':return boolean(args[0].t==='null');case'abs':return args[0].t==='int'?integer(BigInt(args[0].v)<0n?-BigInt(args[0].v):BigInt(args[0].v)):double(Math.abs(numeric(args[0])));case'round':{const digits=args.length===2?index(1):0;if(digits<-15||digits>15)throw Error('Round precision must be between -15 and 15.');if(args[0].t==='int'&&digits>=0)return args[0];const factor=10**digits;return double(Math.round(numeric(args[0])*factor)/factor);}case'min':case'max':return args.reduce((a,b)=>((compare(a,b)<0)===(e.name==='min'))?a:b);default:throw Error('Unknown expression function.');}}
  return run(expr);
}
