import{type Op,type AugmentConfig,titles,validateOp}from'./recipe';import{standard,aggressive}from'./normalize';import{standardQuality,piiKinds}from'./quality';import{defaultChunk}from'./chunker';
export const esc=(value:unknown)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
export const button=(label:string,action:string,kind='secondary',disabled=false)=>`<button type="button" class="${kind}" data-action="${esc(action)}" ${disabled?'disabled':''}>${esc(label)}</button>`;
export type CatalogItem={id:string;category:string;title:string;description:string;op:Op};
export function catalog(columns:string[],textColumn:string):CatalogItem[]{const items:CatalogItem[]=[];const add=(id:string,category:string,description:string,op:Op,title=titles[op.kind])=>items.push({id,category,title,description,op});const column=textColumn||columns[0]||'text';
 add('normalize','Clean','Unicode, whitespace, punctuation and HTML.',{kind:'normalizeText',columns:[],options:standard});add('deep','Clean','NFKC, HTML extraction and punctuation cleanup.',{kind:'normalizeText',columns:[],options:aggressive},'Deep clean');add('nulls','Clean','Map configured sentinel spellings such as N/A to null.',{kind:'unifyNulls',columns:[]});add('types','Clean','Infer consistent types from up to 500 non-null strings.',{kind:'autoType'});
 add('filter','Structure','Keep rows matching a pure expression.',{kind:'filterRows',expression:`tokens(col(${JSON.stringify(column)})) > 10`});add('computed','Structure','Add a column from an expression.',{kind:'addColumn',name:'word_count',expression:`words(col(${JSON.stringify(column)}))`});add('select','Structure','Keep selected columns in order.',{kind:'selectColumns',columns});add('drop','Structure','Remove selected columns.',{kind:'dropColumns',columns:[]});add('rename','Structure','Change a column name without overwriting another.',{kind:'renameColumn',from:columns[0]??'text',to:'renamed'});add('coerce','Structure','Explicitly convert one column; inspect failed values.',{kind:'coerceType',column:columns[0]??'text',type:'string'});
 add('exact','Deduplicate','Compare exact typed values and keep the first row.',{kind:'dedupeExact',columns:[]});add('fuzzy','Deduplicate','MinHash candidates with exact word-shingle Jaccard checks.',{kind:'dedupeFuzzy',column,threshold:.85});
 add('pii','Quality','Review patterns for personal data and credentials.',{kind:'redactPII',columns:[],kinds:[],mode:'tag'});add('quality','Quality','Configurable text-quality heuristics and rejection reasons.',{kind:'qualityFilter',column,rules:standardQuality});add('language','Quality','Filter heuristic language labels, including undetermined.',{kind:'languageFilter',column,allowed:['en'],minConfidence:.3});add('decontaminate','Quality','Compare exact word spans with your evaluation texts.',{kind:'decontaminate',column,evalTexts:[],nGramSize:8});
 add('tokens','Enrich','Count real cl100k ordinary-text tokens.',{kind:'addTokenCount',column});add('lang','Enrich','Add a language label and heuristic score.',{kind:'addLanguage',column});add('score','Enrich','Add the default heuristic quality score.',{kind:'addQualityScore',column});add('chunk','RAG','Sentence-aware chunks with strict token budgets.',{kind:'chunkText',column,config:defaultChunk});add('split','Training','Seeded, optionally stratified partitions.',{kind:'split',train:.9,validation:.05,test:.05,seed:'42',stratifyBy:null});
 for(const[kind,title,description]of[['generateQA','Generate Q&A','Draft one grounded question and answer per row.'],['judgeScore','Judge quality','Request a subjective model score and rationale.'],['rewrite','Rewrite text','Correct style while requesting meaning preservation.'],['classify','Classify / label','Choose from your explicit label set.'],['preferencePair','Synthesize rejected response','Generate a weaker response for a preference pair.']]as const)add(kind,'Optional augmentation',description,{kind:'augment',config:{kind,column,instruction:'',labels:kind==='classify'?['technical','conversational','other']:[],concurrency:4,maxTokens:1024}},title);
 return items;}
const input=(name:string,label:string,value:unknown,type='text',extra='')=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(name:string,label:string,value:unknown,rows=4,max=10000)=>`<label>${esc(label)}<textarea name="${name}" rows="${rows}" maxlength="${max}" spellcheck="false">${esc(value)}</textarea></label>`;
const toggle=(name:string,label:string,on:boolean)=>`<label class="check"><input type="checkbox" name="${esc(name)}" ${on?'checked':''}>${esc(label)}</label>`;
const select=(name:string,label:string,value:unknown,options:readonly string[])=>`<label>${esc(label)}<select name="${name}">${options.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
export function opForm(op:Op,columns:string[]):string{const pick=(name:string,value:string,label='Column')=>input(name,label,value,'text','list="column-list" maxlength="300"'),colset=(selected:string[],allCaption=false)=>`<fieldset><legend>Columns${allCaption?' · none selected means all':''}</legend><div class="checks">${columns.map(c=>`<label class="check"><input type="checkbox" name="columns" value="${esc(c)}" ${selected.includes(c)?'checked':''}>${esc(c)}</label>`).join('')}</div></fieldset>`;let fields='';
 switch(op.kind){case'selectColumns':fields=area('columnOrder','Columns to keep (JSON array, in output order)',JSON.stringify(op.columns,null,2),6,64000)+`<p class="hint">Available source/output names: ${columns.map(esc).join(', ')}. Names must match the dataset at this step.</p>`;break;case'dropColumns':fields=colset(op.columns);break;case'renameColumn':fields=pick('from',op.from)+input('to','New name',op.to,'text','maxlength="300"');break;case'addColumn':fields=input('name','New column name',op.name,'text','maxlength="300"');case'filterRows':fields+=area('expression','Expression',op.expression,3)+`<p class="hint">Pure expressions: <code>len, lower, upper, trim, contains, replace, substr, tokens, words, lang, coalesce, if, col("name with spaces")</code>. Operators: <code>+ - * / % == != &lt; &gt; and or not</code>. Integer overflow is an error.</p>`;break;
 case'normalizeText':fields=colset(op.columns,true)+select('unicodeForm','Unicode normalization',op.options.unicodeForm,['none','nfc','nfkc'])+'<fieldset><legend>Text cleanup</legend><div class="checks">'+Object.entries(op.options).filter(([k])=>k!=='unicodeForm').map(([k,v])=>toggle(k,({trimWhitespace:'Trim whitespace',collapseInnerWhitespace:'Collapse inner whitespace',stripControlCharacters:'Strip control characters',stripZeroWidth:'Strip zero-width characters',canonicalizeQuotes:'Straighten smart quotes',canonicalizeDashes:'Canonicalize dashes',decodeHTMLEntities:'Decode HTML entities',stripHTMLTags:'Extract text from HTML',collapseRepeatedPunctuation:'Collapse repeated punctuation',normalizeNewlines:'Normalize line endings',lowercase:'Lowercase'}as Record<string,string>)[k],!!v)).join('')+'</div></fieldset><p class="hint">Removing zero-width joiners can change emoji sequences and the shaping of some writing systems. Review the cell diff.</p>';break;
 case'unifyNulls':case'dedupeExact':fields=colset(op.columns,true)+(op.kind==='unifyNulls'?'<p class="hint">Empty strings, NA, N/A, NaN, null, none, nil, -, --, ?, missing, #N/A, #NULL!, (null), undefined become null.</p>':'');break;
 case'autoType':fields='<p>Columns with at least 95% consistently parseable strings become bool, int, double or date. Up to 500 non-null strings determine the type; the chosen conversion applies to every row.</p><p class="hint">Inspect failed conversions in the report. UTC is used for dates; ambiguous dotted dates use day/month and slashed dates use month/day.</p>';break;
 case'coerceType':fields=pick('column',op.column)+select('type','Target type',op.type,['string','int','double','bool','date'])+'<p class="hint">Double conversion can round exact decimal text or large integers. Failed conversions become null and retain their original values in the conversion report.</p>';break;
 case'dedupeFuzzy':fields=pick('column',op.column)+input('threshold','Jaccard threshold',op.threshold,'number','min="0.5" max="1" step="0.01"')+'<p class="hint">Near-duplicate candidate recall is approximate. Exact verified pairs form clusters and the first row is retained. Review removed rows before export.</p>';break;
 case'redactPII':fields=colset(op.columns,true)+'<fieldset><legend>Patterns</legend><div class="checks">'+piiKinds.map(k=>toggle('pii-'+k,k,op.kinds.length?op.kinds.includes(k):true)).join('')+'</div></fieldset>'+select('redactionMode','Replacement',op.mode,['tag','hash','remove'])+'<p class="hint">Pattern detection can miss personal data and can flag unrelated text. Stable SHA-256 tags are unsalted pseudonyms, not anonymization.</p>';break;
 case'qualityFilter':fields=pick('column',op.column)+'<div class="form-grid">'+Object.entries(op.rules).map(([k,v])=>typeof v==='boolean'?toggle(k,k==='flagTruncated'?'Flag truncated endings':'Require terminal punctuation',v):input(k,k.replace(/([A-Z])/g,' $1'),v,'number',`min="0" max="${k.includes('Words')?100000:k.includes('WordLength')?100:1}" step="${k.includes('Words')?1:.01}"`)).join('')+'</div><p class="hint">Whitespace-based word counts and repetition rules are heuristics. Review their suitability for your language and domain.</p>';break;
 case'languageFilter':fields=pick('column',op.column)+input('allowed','Allowed language codes (comma separated)',op.allowed.join(', '),'text','maxlength="300"')+input('minConfidence','Minimum heuristic score',op.minConfidence,'number','min="0" max="1" step="0.05"')+'<p class="hint">Supported Latin profiles: en, de, fr, es, it, pt, nl, sv, pl, tr; Japanese and Hangul script heuristics: ja, ko. Shared or ambiguous scripts return und. The score is not a probability; use und with minimum 0 to retain uncertain rows.</p>';break;
 case'decontaminate':fields=pick('column',op.column)+input('nGramSize','Exact word-span length',op.nGramSize,'number','min="1" max="20" step="1"')+`<div id="eval-list">${op.evalTexts.map((t,i)=>`<fieldset class="eval-document"><legend>Evaluation document ${i+1}</legend>${area('eval','Text',t,4,1000000)}${button('Remove document','remove-eval','quiet')}</fieldset>`).join('')}</div><div class="actions">${button('Add text document','add-eval')}${button('Import evaluation file','import-eval')}</div><p class="hint">Rows sharing exact normalized word spans are removed. This does not detect semantic leakage.</p>`;break;
 case'addTokenCount':case'addLanguage':case'addQualityScore':fields=pick('column',op.column);break;
 case'chunkText':fields=pick('column',op.column)+'<div class="form-grid">'+input('targetTokens','Target tokens (including headings)',op.config.targetTokens,'number','min="32" max="8192" step="1"')+input('overlapTokens','Overlap tokens',op.config.overlapTokens,'number','min="0" max="8191" step="1"')+input('minChunkTokens','Minimum tail tokens',op.config.minChunkTokens,'number','min="0" max="8192" step="1"')+'</div>'+toggle('respectMarkdown','Respect Markdown headings',op.config.respectMarkdown)+toggle('includeHeadingContext','Prefix heading breadcrumbs',op.config.includeHeadingContext)+'<p class="hint">Every chunk stays within the target. A word longer than the budget is split at grapheme boundaries. An oversized heading requires a larger budget or disabled heading context.</p>';break;
 case'split':fields='<div class="form-grid">'+input('train','Train fraction',op.train,'number','min="0" max="1" step="0.01"')+input('validation','Validation fraction',op.validation,'number','min="0" max="1" step="0.01"')+input('test','Test fraction',op.test,'number','min="0" max="1" step="0.01"')+'</div>'+input('seed','Unsigned 64-bit seed',op.seed,'text','inputmode="numeric" maxlength="20"')+pick('stratifyBy',op.stratifyBy??'','Stratify by (leave blank for none)')+'<p class="hint">Fractions must sum to 1. The same data and seed reproduce the Windows split. Swift and Windows shuffle implementations can assign different rows.</p>';break;
 case'augment':fields=pick('column',op.config.column)+area('instruction','Additional guidance',op.config.instruction,3,4000)+(op.config.kind==='classify'?area('labels','Allowed labels (one per line)',op.config.labels.join('\n'),4,10000):'')+'<div class="form-grid">'+input('concurrency','Maximum concurrent requests',op.config.concurrency,'number','min="1" max="16" step="1"')+input('maxTokens','Maximum output tokens per request',op.config.maxTokens,'number','min="128" max="8192" step="1"')+'</div><p class="hint">Skipped in sampled previews. Full runs use the chosen demo or provider. Sources above 24,000 characters / 48 KB must be chunked first. Completed responses are cached for resume; network failures are not automatically retried.</p>';break;
 }
 return `<form id="op-form"><datalist id="column-list">${columns.map(c=>`<option value="${esc(c)}"></option>`).join('')}</datalist>${fields}<p id="form-error" class="error" role="alert"></p><div class="modal-actions">${button('Cancel','close-modal') }<button type="submit" class="primary">Save step</button></div></form>`;
}
export function readOpForm(form:HTMLFormElement,previous:Op):Op{const data=new FormData(form),str=(name:string)=>String(data.get(name)??''),num=(name:string)=>{const s=str(name);if(!s.trim())throw Error('A numeric field is blank.');return Number(s);},bool=(name:string)=>data.has(name),columns=()=>data.getAll('columns').map(String);let next:any={kind:previous.kind};
 switch(previous.kind){case'selectColumns':try{next.columns=JSON.parse(str('columnOrder'));}catch{throw Error('Enter a JSON array of column names, such as [\"message\", \"ticket_id\"].');}break;case'dropColumns':case'unifyNulls':case'dedupeExact':next.columns=columns();break;case'renameColumn':next.from=str('from');next.to=str('to');break;case'addColumn':next.name=str('name');case'filterRows':next.expression=str('expression');break;case'normalizeText':next.columns=columns();next.options={unicodeForm:str('unicodeForm')};for(const key of Object.keys(standard))if(key!=='unicodeForm')next.options[key]=bool(key);break;case'autoType':break;case'coerceType':next.column=str('column');next.type=str('type');break;case'dedupeFuzzy':next.column=str('column');next.threshold=num('threshold');break;case'redactPII':next.columns=columns();next.kinds=piiKinds.filter(k=>bool('pii-'+k));if(!next.kinds.length)throw Error('Select at least one PII pattern or remove this step.');next.mode=str('redactionMode');break;case'qualityFilter':next.column=str('column');next.rules={};for(const[k,v]of Object.entries(standardQuality))next.rules[k]=typeof v==='boolean'?bool(k):num(k);break;case'languageFilter':next.column=str('column');next.allowed=str('allowed').split(',').map(s=>s.trim()).filter(Boolean);next.minConfidence=num('minConfidence');break;case'decontaminate':next.column=str('column');next.nGramSize=num('nGramSize');next.evalTexts=data.getAll('eval').map(String).filter(s=>s.trim());break;case'addTokenCount':case'addLanguage':case'addQualityScore':next.column=str('column');break;case'chunkText':next.column=str('column');next.config={targetTokens:num('targetTokens'),overlapTokens:num('overlapTokens'),minChunkTokens:num('minChunkTokens'),respectMarkdown:bool('respectMarkdown'),includeHeadingContext:bool('includeHeadingContext')};break;case'split':next.train=num('train');next.validation=num('validation');next.test=num('test');next.seed=str('seed');next.stratifyBy=str('stratifyBy')||null;break;case'augment':next.config={kind:previous.config.kind,column:str('column'),instruction:str('instruction'),labels:previous.config.kind==='classify'?str('labels').split('\n').map(s=>s.trim()).filter(Boolean):[],concurrency:num('concurrency'),maxTokens:num('maxTokens')};break;
 }
 return validateOp(next);
}
