import { type Dataset, type DataRow, type Value, NIL, string, integer, double, display, same, truthy, cellKey, requireColumn, uniqueColumn, validateDataset, limits, checkCancelled, splitMix, hash64 } from './model';
import { type Op, type Step, type AugmentConfig, validateOp, titles } from './recipe';
import { normalize } from './normalize';
import { inferType, coerce, isNullString } from './types';
import { exactDedupe, fuzzyDedupe } from './dedupe';
import { parseExpression, evaluateExpression } from './expression';
import { quality, language, redactPII, ngrams, evaluationIndex } from './quality';
import { chunkText } from './chunker';
import type { Tokenizer } from './tokenizer';
export type Metrics={stepId:string;opName:string;rowsIn:number;rowsOut:number;cellsChanged:number;notes:Record<string,string>};
export type RejectedBatch={stepId:string;opName:string;columns:string[];rows:{record:DataRow;reason:string}[]};
export type ConversionIssue={stepId:string;recordId:number;column:string;original:Value;target:string};
export type ExecutionResult={dataset:Dataset;metrics:Metrics[];rejected:RejectedBatch[];conversions:ConversionIssue[];complete:boolean;skippedAugmentations:number};
export type AugmentRunner=(config:AugmentConfig,dataset:Dataset,signal?:AbortSignal)=>Promise<{dataset:Dataset;notes:Record<string,string>}>;
export type RunOptions={signal?:AbortSignal;preview?:boolean;augment?:AugmentRunner;progress?:(step:number,total:number,name:string)=>void};
export function splitDataset(ds:Dataset,op:Extract<Op,{kind:'split'}>):Dataset{const groups=new Map<string,number[]>(),idx=op.stratifyBy?requireColumn(ds,op.stratifyBy):-1;for(const r of ds.records){const key=idx>=0?cellKey(r.values[idx]):'';const ids=groups.get(key)??[];ids.push(r.id);groups.set(key,ids);}const assignment=new Map<number,string>();
  for(const [key,ids]of [...groups].sort(([a],[b])=>a<b?-1:a>b?1:0)){const random=splitMix(BigInt(op.seed)+hash64(key+'|'+ids.join(','))),shuffled=[...ids];for(let i=shuffled.length-1;i>0;i--){const range=BigInt(i+1),ceiling=(1n<<64n)-((1n<<64n)%range);let n=random();while(n>=ceiling)n=random();const j=Number(n%range);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}
    const quotas=[op.train,op.validation,op.test].map(f=>f*ids.length),counts=quotas.map(Math.floor),remainders=quotas.map((q,i)=>({i,remainder:q-counts[i]})).sort((a,b)=>b.remainder-a.remainder||a.i-b.i);for(let left=ids.length-counts.reduce((a,b)=>a+b,0),j=0;left>0;left--,j++)counts[remainders[j].i]++;shuffled.forEach((id,i)=>assignment.set(id,i<counts[0]?'train':i<counts[0]+counts[1]?'validation':'test'));}
  return{columns:[...ds.columns,uniqueColumn(ds.columns,'split')],records:ds.records.map(r=>({id:r.id,values:[...r.values,string(assignment.get(r.id)!)]}))};
}
export async function runPipeline(input:Dataset,steps:Step[],tokenizer:Tokenizer,options:RunOptions={}):Promise<ExecutionResult>{if(steps.length>limits.steps)throw Error('Pipeline exceeds 100 steps.');let current=validateDataset(input);const metrics:Metrics[]=[],rejected:RejectedBatch[]=[],conversions:ConversionIssue[]=[];const active=steps.filter(s=>s.enabled);let skippedAugmentations=0;
  for(let stepIndex=0;stepIndex<active.length;stepIndex++){checkCancelled(options.signal);const step=active[stepIndex],op=validateOp(step.op);options.progress?.(stepIndex,active.length,titles[op.kind]);checkCancelled(options.signal);if(options.preview&&op.kind==='augment'){skippedAugmentations++;continue;}
    const before=current,m:Metrics={stepId:step.id,opName:titles[op.kind],rowsIn:before.records.length,rowsOut:0,cellsChanged:0,notes:{}},drops:RejectedBatch={stepId:step.id,opName:m.opName,columns:before.columns,rows:[]};let out:Dataset={columns:[...before.columns],records:before.records.map(r=>({id:r.id,values:[...r.values]}))};
    const column=(name:string)=>requireColumn(before,name),indexes=(columns:string[])=>columns.length?columns.map(column):before.columns.map((_,i)=>i),set=(r:DataRow,i:number,v:Value)=>{if(!same(r.values[i],v)){r.values[i]=v;m.cellsChanged++;}},append=(base:string,values:Value[])=>{const name=uniqueColumn(out.columns,base);out.columns.push(name);out.records.forEach((r,i)=>r.values.push(values[i]));m.cellsChanged+=values.length;m.notes.addedColumn=name;},filter=(predicate:(row:DataRow)=>string|null)=>{out.records=out.records.filter(r=>{checkCancelled(options.signal);const reason=predicate(r);if(reason!==null){drops.rows.push({record:r,reason});return false;}return true;});};
    try{
      switch(op.kind){
        case'selectColumns':case'dropColumns':{const selected=indexes(op.columns);const keep=op.kind==='selectColumns'?op.columns.map(column):out.columns.map((_,i)=>i).filter(i=>!selected.includes(i)||!op.columns.length);if(!keep.length)throw Error('Select at least one output column.');out={columns:keep.map(i=>before.columns[i]),records:before.records.map(r=>({id:r.id,values:keep.map(i=>r.values[i])}))};break;}
        case'renameColumn':{const i=column(op.from);if(op.to!==op.from&&out.columns.includes(op.to))throw Error('Renamed column would overwrite an existing column.');out.columns[i]=op.to;break;}
        case'addColumn':{if(out.columns.includes(op.name))throw Error('Computed column already exists.');const expr=parseExpression(op.expression),values=before.records.map(r=>{checkCancelled(options.signal);try{return evaluateExpression(expr,before,r,tokenizer);}catch(e){throw Error(`Row ${r.id}: ${(e as Error).message}`);}});append(op.name,values);break;}
        case'filterRows':{const expr=parseExpression(op.expression);filter(r=>truthy(evaluateExpression(expr,before,r,tokenizer))?null:'Filter expression was false.');break;}
        case'normalizeText':{for(const r of out.records){checkCancelled(options.signal);for(const i of indexes(op.columns)){const v=r.values[i];if(v.t==='string'){const s=normalize(v.v,op.options);set(r,i,s?string(s):NIL);}}}m.notes.zeroWidth=op.options.stripZeroWidth?'Enabled; can alter emoji joins and writing-system shaping.':'Preserved';break;}
        case'unifyNulls':for(const r of out.records){checkCancelled(options.signal);for(const i of indexes(op.columns)){const v=r.values[i];if(v.t==='string'&&isNullString(v.v))set(r,i,NIL);}}break;
        case'autoType':case'coerceType':{let losses=0,approximate=0;const idxs=op.kind==='coerceType'?[column(op.column)]:out.columns.map((_,i)=>i);for(const i of idxs){const type=op.kind==='coerceType'?op.type:inferType(out.records.map(r=>r.values[i]));if(op.kind==='autoType'&&type==='string')continue;m.notes['type:'+out.columns[i]]=type;for(const r of out.records){checkCancelled(options.signal);const old=r.values[i],value=coerce(old,type);if(value.t==='null'&&old.t!=='null'&&!(old.t==='string'&&isNullString(old.v))){losses++;conversions.push({stepId:step.id,recordId:r.id,column:out.columns[i],original:old,target:type});}if(type==='double'&&(old.t==='decimal'||old.t==='int'&&!Number.isSafeInteger(Number(old.v))))approximate++;set(r,i,value);}}m.notes.failedConversions=String(losses);if(approximate)m.notes.approximateDoubleConversions=String(approximate);m.notes.dateConvention='UTC; ambiguous dotted dates use day/month; ambiguous slashed/dashed dates use month/day.';break;}
        case'dedupeExact':case'dedupeFuzzy':{const found=op.kind==='dedupeFuzzy'?fuzzyDedupe(before,op.column,op.threshold,options.signal):exactDedupe(before,op.columns,options.signal),removed=new Set(found.droppedIDs);filter(r=>removed.has(r.id)?'Duplicate cluster; earliest row retained.':null);m.notes.clusters=String(found.clusters.length);m.notes.candidatePairs=String(found.candidates);m.notes.method=found.method;break;}
        case'redactPII':{const counts:Record<string,number>=Object.create(null);for(const r of out.records){checkCancelled(options.signal);for(const i of indexes(op.columns)){const old=r.values[i];if(old.t!=='string')continue;const redacted=await redactPII(old.v,op.kinds,op.mode);set(r,i,string(redacted.text));for(const[k,n]of Object.entries(redacted.counts))counts[k]=(counts[k]??0)+n;}}for(const[k,n]of Object.entries(counts))m.notes[k]=String(n);m.notes.scope='Pattern-based detection can miss PII and can flag non-PII; review before sharing. Hashes are unsalted pseudonyms, not anonymization.';break;}
        case'qualityFilter':{const i=column(op.column);filter(r=>{const verdict=quality(display(r.values[i]),op.rules);return verdict.passed?null:verdict.reasons.join('; ');});m.notes.method='Configurable text heuristics, including whitespace-based word counts; language/domain review required.';break;}
        case'languageFilter':{const i=column(op.column);filter(r=>{const d=language(display(r.values[i]));return op.allowed.includes(d.code)&&d.confidence>=op.minConfidence?null:`Language ${d.code}, heuristic score ${d.confidence.toFixed(3)}; ${d.method}${d.script?' ('+d.script+')':''}`;});m.notes.method='Ten Latin stopword profiles; Japanese/Hangul script heuristics. Shared scripts remain undetermined.';break;}
        case'decontaminate':{const i=column(op.column),index=evaluationIndex(op.evalTexts,op.nGramSize);filter(r=>{let hits=0;for(const g of ngrams(display(r.values[i]),op.nGramSize))if(index.has(g))hits++;return hits?`${hits} exact normalized ${op.nGramSize}-word n-gram matches in evaluation text.`:null;});m.notes.indexedNGrams=String(index.size);m.notes.method='Exact normalized word overlap; not semantic leakage detection.';break;}
        case'addTokenCount':{const i=column(op.column);append('token_count',out.records.map(r=>{checkCancelled(options.signal);return integer(tokenizer.count(display(r.values[i])));}));m.notes.tokenizer=tokenizer.name;break;}
        case'addLanguage':{const i=column(op.column),detections=out.records.map(r=>language(display(r.values[i])));append('lang',detections.map(d=>string(d.code)));append('lang_confidence',detections.map(d=>double(d.confidence)));m.notes.method='Heuristic score is not a probability; shared scripts may return und.';break;}
        case'addQualityScore':{const i=column(op.column);append('quality_score',out.records.map(r=>double(quality(display(r.values[i])).score)));m.notes.method='1 minus 0.25 per failed default heuristic, floored at zero.';break;}
        case'chunkText':{const i=column(op.column),names:string[]=[];for(const base of ['chunk_index','chunk_tokens','heading_path']){const name=uniqueColumn(out.columns,base);out.columns.push(name);names.push(name);}let nextID=Math.max(-1,...before.records.map(r=>r.id))+1;out.records=[];for(const r of before.records){checkCancelled(options.signal);const chunks=chunkText(display(r.values[i]),op.config,tokenizer,options.signal);if(!chunks.length)drops.rows.push({record:r,reason:'Empty text produced no chunks.'});for(let k=0;k<chunks.length;k++){if(out.records.length>=limits.rows)throw Error('Chunked dataset exceeds 50,000 rows.');const c=chunks[k],values=[...r.values];values[i]=string(c.text);out.records.push({id:k===0?r.id:nextID++,values:[...values,integer(c.index),integer(c.tokenCount),string(c.headingPath)]});}}m.cellsChanged=out.records.length*4;m.notes.tokenizer=tokenizer.name;m.notes.addedColumns=names.join(', ');m.notes.budget='Every emitted chunk including heading is at or below target; oversized words split at grapheme boundaries.';break;}
        case'split':out=splitDataset(out,op);m.cellsChanged=out.records.length;m.notes.seed=op.seed;m.notes.method='Windows v1 SplitMix64/Fisher–Yates, largest-remainder counts per stratum. Repeatable within this engine; not bit-identical to Swift shuffle.';break;
        case'augment':{if(!options.augment)throw Error('Choose a provider and review augmentation consent before running.');const result=await options.augment(op.config,before,options.signal);out=result.dataset;Object.assign(m.notes,result.notes);break;}
      }
      checkCancelled(options.signal);current=validateDataset(out);m.rowsOut=current.records.length;metrics.push(m);if(drops.rows.length)rejected.push(drops);
    }catch(e){if((e as Error).name==='AbortError')throw e;throw Error(`Step ${stepIndex+1} (${m.opName}): ${(e as Error).message}`);}
    await new Promise<void>(resolve=>setTimeout(resolve,0));
  }
  checkCancelled(options.signal);return{dataset:current,metrics,rejected,conversions,complete:!options.preview,skippedAugmentations};
}
