import{type Dataset,type ImportResult,type Value,validateDataset,validateValue,limits}from'./model';import{type Step,validateOp,makeStep}from'./recipe';import{type ExecutionResult,type Metrics,type RejectedBatch,type ConversionIssue}from'./pipeline';import{type AugmentCache}from'./augmentation';import{standard}from'./normalize';import{defaultChunk}from'./chunker';
export type Workspace={version:1;revision:number;theme:'system'|'light'|'dark';reduceMotion:boolean;mode:'curate'|'retrieve';screen:'pipeline'|'preview'|'report'|'export'|'settings';source:ImportResult|null;steps:Step[];undo:Step[][];redo:Step[][];completed:{revision:number;result:ExecutionResult}|null;cache:AugmentCache;priceInput:number|null;priceOutput:number|null};
export const MAX_WORKSPACE_BYTES=256*1024*1024;
export function emptyWorkspace():Workspace{return{version:1,revision:0,theme:'system',reduceMotion:false,mode:'curate',screen:'pipeline',source:null,steps:[],undo:[],redo:[],completed:null,cache:Object.create(null),priceInput:null,priceOutput:null};}
function obj(x:unknown):Record<string,unknown>{if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Invalid workspace object.');return x as Record<string,unknown>;}
function text(x:unknown,max=1000):string{if(typeof x!=='string'||x.length>max)throw Error('Invalid workspace text.');return x;}
function int(x:unknown,max=Number.MAX_SAFE_INTEGER):number{if(typeof x!=='number'||!Number.isSafeInteger(x)||x<0||x>max)throw Error('Invalid workspace count.');return x;}
function choice<T extends string>(x:unknown,values:readonly T[]):T{if(typeof x!=='string'||!values.includes(x as T))throw Error('Invalid workspace option.');return x as T;}
function bool(x:unknown):boolean{if(typeof x!=='boolean')throw Error('Invalid workspace boolean.');return x;}
function array(x:unknown,max:number):unknown[]{if(!Array.isArray(x)||x.length>max)throw Error('Invalid workspace list.');return x;}
function details(x:unknown,max=200):Record<string,string>{const entries=Object.entries(obj(x));if(entries.length>max)throw Error('Too many metadata fields.');const out:Record<string,string>=Object.create(null);for(const[k,v]of entries)out[text(k,400)]=text(v,8000);return out;}
export function validateSteps(x:unknown):Step[]{const ids=new Set<string>();return array(x,limits.steps).map(v=>{const s=obj(v),id=text(s.id,80);if(!id||ids.has(id))throw Error('Invalid or duplicate step identity.');ids.add(id);return{id,enabled:bool(s.enabled),op:validateOp(s.op)};});}
export function validateImport(x:unknown):ImportResult{const s=obj(x),dataset=validateDataset(s.dataset);return{dataset,source:text(s.source,1000),format:choice(s.format,['csv','tsv','json','jsonl','text','markdown','html','sqlite','folder']),details:details(s.details),warnings:array(s.warnings,1000).map(s=>text(s,10000)),rejected:array(s.rejected,50000).map(v=>{const r=obj(v);return{row:int(r.row,50001),reason:text(r.reason,10000),original:text(r.original,limits.cellChars)};})};}
function validateMetrics(x:unknown):Metrics[]{return array(x,100).map(v=>{const m=obj(v);return{stepId:text(m.stepId,80),opName:text(m.opName,200),rowsIn:int(m.rowsIn,50000),rowsOut:int(m.rowsOut,50000),cellsChanged:int(m.cellsChanged,10000000),notes:details(m.notes,500)};});}
export function validateResult(x:unknown):ExecutionResult{const r=obj(x),dataset=validateDataset(r.dataset),rejected:RejectedBatch[]=array(r.rejected,100).map(v=>{const b=obj(v),rows=array(b.rows,50000).map(v=>obj(v)),checked=validateDataset({columns:b.columns,records:rows.map(r=>r.record)});return{stepId:text(b.stepId,80),opName:text(b.opName,200),columns:checked.columns,rows:rows.map((r,i)=>({record:checked.records[i],reason:text(r.reason,10000)}))};}),conversions:ConversionIssue[]=array(r.conversions,5000000).map(v=>{const c=obj(v);return{stepId:text(c.stepId,80),recordId:int(c.recordId),column:text(c.column,300),original:validateValue(c.original),target:choice(c.target,['int','double','bool','date','string'])};});return{dataset,metrics:validateMetrics(r.metrics),rejected,conversions,complete:bool(r.complete),skippedAugmentations:int(r.skippedAugmentations,100)};}
export function validateWorkspace(input:unknown):Workspace{const s=obj(input);if(s.version!==1)throw Error('Unsupported workspace version.');const revision=int(s.revision),source=s.source===null?null:validateImport(s.source),steps=validateSteps(s.steps),cache:AugmentCache=Object.create(null),entries=Object.entries(obj(s.cache));if(entries.length>50000)throw Error('Augmentation cache exceeds 50,000 entries.');let cacheBytes=0;for(const[k,v]of entries){if(!/^[0-9a-f]{64}$/.test(k))throw Error('Invalid checkpoint identity.');const values=array(v,2).map(validateValue);cacheBytes+=JSON.stringify(values).length;if(cacheBytes>32*1024*1024)throw Error('Augmentation cache exceeds 64 MiB of text.');cache[k]=values;}
  let completed:Workspace['completed']=null;if(s.completed!==null){const c=obj(s.completed),result=validateResult(c.result);if(!result.complete)throw Error('A sampled preview cannot be restored as a full result.');completed={revision:int(c.revision),result};if(completed.revision>revision||!source)throw Error('Completed result does not belong to this workspace.');}
  const history=(x:unknown)=>array(x,100).map(validateSteps),price=(x:unknown)=>{if(x===null)return null;if(typeof x!=='number'||!Number.isFinite(x)||x<0||x>1000000)throw Error('Invalid optional provider price.');return x;};
  return{version:1,revision,theme:choice(s.theme,['system','light','dark']),reduceMotion:bool(s.reduceMotion),mode:choice(s.mode,['curate','retrieve']),screen:choice(s.screen,['pipeline','preview','report','export','settings']),source,steps,undo:history(s.undo),redo:history(s.redo),completed,cache,priceInput:price(s.priceInput),priceOutput:price(s.priceOutput)};
}
export function parseWorkspace(text:string):Workspace{if(new TextEncoder().encode(text).length>MAX_WORKSPACE_BYTES)throw Error('Workspace exceeds 256 MiB.');return validateWorkspace(JSON.parse(text));}
export function stringifyWorkspace(s:Workspace):string{const raw=JSON.stringify(s);if(new TextEncoder().encode(raw).length>MAX_WORKSPACE_BYTES)throw Error('Workspace exceeds 256 MiB; export and start a smaller batch.');return raw;}
export function guessTextColumn(ds:Dataset):string{let best=ds.columns[0]??'text',score=-1;ds.columns.forEach((c,i)=>{let length=0;for(const r of ds.records.slice(0,50)){const v=r.values[i];if(v.t==='string')length+=v.v.length;}if(length>score){score=length;best=c;}});return best;}
export function starterSteps(mode:Workspace['mode'],ds:Dataset):Step[]{const column=guessTextColumn(ds);return(mode==='curate'?[{kind:'normalizeText' as const,columns:[],options:standard},{kind:'unifyNulls' as const,columns:[]},{kind:'autoType' as const},{kind:'dedupeExact' as const,columns:[]}]:[{kind:'normalizeText' as const,columns:[],options:standard},{kind:'chunkText' as const,column,config:defaultChunk},{kind:'addTokenCount' as const,column}]).map(makeStep);}
export function editSteps(s:Workspace,steps:Step[]):Workspace{const checked=validateSteps(steps),undo=[...s.undo,s.steps];while(undo.length>100||JSON.stringify(undo).length>4*1024*1024)undo.shift();return{...s,revision:s.revision+1,steps:checked,undo,redo:[]};}
export function historyStep(s:Workspace,direction:'undo'|'redo'):Workspace{const stack=s[direction];if(!stack.length)return s;const previous=stack.at(-1)!;return{...s,revision:s.revision+1,steps:previous,[direction]:stack.slice(0,-1),[direction==='undo'?'redo':'undo']:[...s[direction==='undo'?'redo':'undo'],s.steps].slice(-100)};}
