const path=require('node:path');
class EngineBridge{
 constructor(utilityProcess,host,progress){this.utilityProcess=utilityProcess;this.host=host;this.progress=progress;this.child=null;this.next=0;this.pending=new Map();this.generation=0;}
 async start(state,storageError=''){if(this.child)await this.stop();const generation=++this.generation,child=this.child=this.utilityProcess.fork(path.join(__dirname,'worker.cjs'),[],{stdio:'ignore',serviceName:'Alembic dataset engine'});child.on('message',async data=>{if(generation!==this.generation)return;if(data.event==='progress'){this.progress(data.text);return;}if(data.host){try{const value=await this.host(data.command,data.args);if(generation===this.generation)child.postMessage({reply:data.host,value});}catch(e){if(generation===this.generation)child.postMessage({reply:data.host,error:e.message});}return;}const p=this.pending.get(data.id);if(p){this.pending.delete(data.id);clearTimeout(p.timer);data.error?p.reject(Error(data.error)):p.resolve(data.value);}});child.once('exit',code=>{if(generation!==this.generation)return;this.child=null;for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('Alembic engine stopped ('+code+'). Reload the last saved workspace.'));}this.pending.clear();});return this.call('initialize',{state,storageError},30000);}
 call(command,args={},timeout=0){if(!this.child)return Promise.reject(Error('Workspace engine is not running. Use Cancel to reload the saved workspace.'));if(this.pending.size>=16)return Promise.reject(Error('Too many pending workspace requests.'));const id=++this.next;return new Promise((resolve,reject)=>{const timer=timeout?setTimeout(()=>{this.pending.delete(id);reject(Error('Workspace request timed out. Cancel to recover the last save.'));},timeout):null;this.pending.set(id,{resolve,reject,timer});this.child.postMessage({id,command,args});});}
 async stop(){const child=this.child;this.child=null;this.generation++;for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('Operation cancelled. The last completed save is preserved.'));}this.pending.clear();if(child)await new Promise(resolve=>{const timer=setTimeout(resolve,5000);child.once('exit',()=>{clearTimeout(timer);resolve();});child.kill();});}
}
async function sqliteJob(utilityProcess,args,onChild=()=>{},timeout=35000){const fs=require('node:fs/promises'),os=require('node:os'),base=path.resolve(os.tmpdir()),temporaryRoot=await fs.mkdtemp(path.join(base,'alembic-query-'));if(path.dirname(temporaryRoot)!==base||!path.basename(temporaryRoot).startsWith('alembic-query-'))throw Error('Invalid SQLite temporary directory.');return new Promise((resolve,reject)=>{let child,done=false,exited=false,timer;const finish=async(error,value)=>{if(done)return;done=true;clearTimeout(timer);if(child&&!exited){await new Promise(r=>{child.once('exit',()=>{exited=true;r();});child.kill();});}onChild(null);try{await fs.rm(temporaryRoot,{recursive:true,force:true});}catch(e){error=Error((error?error.message+' ':'')+'Temporary SQLite snapshot could not be removed: '+temporaryRoot);}error?reject(error):resolve(value);};try{child=utilityProcess.fork(path.join(__dirname,'sqlite-worker.cjs'),[],{stdio:'ignore',serviceName:'Alembic SQLite snapshot'});child.once('exit',()=>{exited=true;void finish(Error('SQLite import stopped before completion.'));});child.once('message',data=>void finish(data.error?Error(data.error):null,data.value));timer=setTimeout(()=>void finish(Error('SQLite exceeded its time limit. The isolated query was stopped; the source database is unchanged.')),timeout);onChild(child);child.postMessage({...args,temporaryRoot});}catch(e){void finish(e);}});}
module.exports={EngineBridge,sqliteJob};
