const fs=require('node:fs/promises'),path=require('node:path'),{importBytes}=require('./importers.cjs'),{validateDataset,NIL,uniqueColumn}=require('./model.cjs');
const MAX_INPUT=32*1024*1024,formats=new Set(['.csv','.tsv','.json','.jsonl','.ndjson','.txt','.md','.markdown','.html','.htm','.py','.js','.ts','.tsx','.jsx','.swift','.rs','.go','.java','.c','.cpp','.h','.sql','.log']);
function localPath(raw){if(typeof raw!=='string'||raw.length>30000||! /^[A-Za-z]:[\\/]/.test(raw)||raw.slice(2).includes(':')||raw.split(/[\\/]/).slice(1).some(s=>s==='..'||s==='.'||/[. ]$/.test(s)))throw Error('Choose a local Windows path without aliases or alternate streams.');return path.resolve(raw);}
const identity=s=>[s.dev,s.ino,s.size,s.mtimeNs,s.ctimeNs].map(String).join(':');
async function inspect(raw,directory=false){const target=localPath(raw),stat=await fs.lstat(target,{bigint:true});if(stat.isSymbolicLink()||(directory?!stat.isDirectory():!stat.isFile())||(await fs.realpath(target)).toLowerCase()!==target.toLowerCase())throw Error('Links, junctions and non-regular paths are not imported.');return{target,stat};}
async function readStable(raw,maximum=MAX_INPUT){const {target,stat}=await inspect(raw);if(stat.size>BigInt(maximum))throw Error('Selected file exceeds the import limit.');const handle=await fs.open(target,'r');try{if(identity(await handle.stat({bigint:true}))!==identity(stat))throw Error('Selected file changed before reading.');const bytes=Buffer.alloc(Number(stat.size));let count=0;while(count<bytes.length){const r=await handle.read(bytes,count,bytes.length-count,count);if(!r.bytesRead)throw Error('Selected file shortened during reading.');count+=r.bytesRead;}if(identity(await handle.stat({bigint:true}))!==identity(stat)||identity((await inspect(target)).stat)!==identity(stat))throw Error('Selected file changed during reading.');return bytes;}finally{await handle.close();}}
async function importFile(file,options){return importBytes(await readStable(file),path.basename(file),options);}
async function importFolder(raw,options,progress=()=>{}){const{target}=await inspect(raw,true),pending=[{directory:target,depth:0}],files=[],skipped=[];let seen=0,bytes=0;while(pending.length){const{directory,depth}=pending.pop();if(depth>32)throw Error('Folder exceeds 32 nested levels.');await inspect(directory,true);const names=(await fs.readdir(directory)).sort();for(const name of names){if(++seen>10000)throw Error('Folder exceeds 10,000 entries.');const file=path.join(directory,name),stat=await fs.lstat(file,{bigint:true});if(stat.isSymbolicLink()){skipped.push(path.relative(target,file)+' (link)');continue;}if(stat.isDirectory()){pending.push({directory:file,depth:depth+1});continue;}if(!stat.isFile()||!formats.has(path.extname(name).toLowerCase())){skipped.push(path.relative(target,file));continue;}files.push(file);bytes+=Number(stat.size);if(files.length>2000||bytes>MAX_INPUT)throw Error('Folder exceeds 2,000 supported files or 32 MiB combined input.');}}files.sort();if(!files.length)throw Error('Folder contains no supported text datasets.');const imported=[],columns=[];let rows=0;for(const file of files){progress('Importing '+(imported.length+1)+'/'+files.length+' files');const result=await importFile(file,options);rows+=result.dataset.records.length;if(rows>50000)throw Error('Combined folder exceeds 50,000 rows.');for(const c of result.dataset.columns)if(!columns.includes(c)){columns.push(c);if(columns.length>=200)throw Error('Combined folder needs a source-file column within the 200-column limit.');}imported.push({file:path.relative(target,file),result});}const sourceColumn=uniqueColumn(columns,'source_file');columns.push(sourceColumn);const records=[],rejected=[],warnings=[];for(const{file,result}of imported){const indexes=result.dataset.columns.map(c=>columns.indexOf(c));for(const row of result.dataset.records){const values=columns.map(()=>NIL);indexes.forEach((idx,i)=>values[idx]=row.values[i]);values[columns.length-1]={t:'string',v:file};records.push({id:records.length,values});}for(const r of result.rejected)rejected.push({...r,reason:file+': '+r.reason});warnings.push(...result.warnings.map(w=>file+': '+w));}if(warnings.length>1000)throw Error('Too many import warnings; import smaller groups.');return{source:path.basename(target)+' ('+files.length+' files)',format:'folder',dataset:validateDataset({columns,records}),rejected,warnings:[...warnings,...(skipped.length?[skipped.length+' unsupported/link entries skipped; first 50: '+skipped.slice(0,50).join('; ')]:[])],details:{files:String(files.length),sourceColumn,skipped:String(skipped.length)}};}
module.exports={localPath,inspect,readStable,importFile,importFolder,MAX_INPUT};
