const {validateOp}=require('./recipe.cjs');
const object=x=>{if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Invalid request object.');return x;};
const text=(x,max,empty=true)=>{if(typeof x!=='string'||x.length>max||(!empty&&!x.trim()))throw Error('Invalid request text.');return x;};
const number=(x,min,max)=>{if(!Number.isSafeInteger(x)||x<min||x>max)throw Error('Invalid request number.');return x;};
const choice=(x,choices)=>{if(!choices.includes(x))throw Error('Unsupported request option.');return x;};
const bool=x=>{if(typeof x!=='boolean')throw Error('Invalid request flag.');return x;};
function importOptions(x={}){object(x);const o={};if(x.format!==undefined)o.format=choice(x.format,['auto','csv','tsv','json','jsonl','text','markdown','html']);if(x.header!==undefined)o.header=choice(x.header,['auto','yes','no']);if(x.textMode!==undefined)o.textMode=choice(x.textMode,['wholeFile','paragraphs','lines','markdownSections']);if(x.delimiter!==undefined)o.delimiter=choice(x.delimiter,[',','\t',';','|']);if(x.jsonPath!==undefined){if(!Array.isArray(x.jsonPath)||x.jsonPath.length>32)throw Error('Invalid JSON array path.');o.jsonPath=x.jsonPath.map(v=>text(v,300,false));}return o;}
function exportArgs(x){const kind=choice(x.kind,['backup','recipe','card-md','card-json','import-rejections','pipeline-rejections','conversions','json','jsonl','csv','shaped','schema-quarantine']);const out={kind};if(x.schema!==undefined)out.schema=choice(x.schema,['alpaca','openaiMessages','anthropicTurns','chatml','dpo','completion','corpus','ragChunks']);if(x.mapping!==undefined){object(x.mapping);if(Object.keys(x.mapping).length>12)throw Error('Too many mapped fields.');out.mapping=Object.fromEntries(Object.entries(x.mapping).map(([k,v])=>[text(k,100,false),text(v,300)]));}if(x.spreadsheetSafe!==undefined)out.spreadsheetSafe=bool(x.spreadsheetSafe);if(x.splitColumn!==undefined)out.splitColumn=text(x.splitColumn,300);if(x.splitValue!==undefined)out.splitValue=choice(x.splitValue,['train','validation','test']);return out;}
function validate(command,args={}){text(command,50,false);const x=object(args);switch(command){case'overview':case'report':case'undo':case'redo':case'preview':case'run':case'new':case'cancel':case'recover':case'provider-status':case'provider-forget':case'prepare-run':case'import-backup':return{};case'page':return{view:choice(x.view,['source','preview','full']),offset:number(x.offset??0,0,50000),query:text(x.query??'',300),sortColumn:text(x.sortColumn??'',300),descending:bool(x.descending??false)};case'cell':return{view:choice(x.view,['source','preview','full']),id:number(x.id,0,Number.MAX_SAFE_INTEGER),column:text(x.column,300,false)};case'profile':return{view:choice(x.view,['source','preview','full']),column:text(x.column,300,false)};case'steps':{if(!Array.isArray(x.steps)||x.steps.length>100||JSON.stringify(x.steps).length>8_000_000)throw Error('Invalid pipeline size.');return{steps:x.steps.map(s=>({id:text(s.id,80,false),enabled:bool(s.enabled),op:validateOp(s.op)}))};}case'preset':return{name:choice(x.name,['training','rag','privacy','dedupe'])};case'recipe':return{text:text(x.text,8_000_000,false)};case'import-text':{const source=text(x.source,300,false),raw=text(x.text,32*1024*1024,false);if(Buffer.byteLength(raw)>32*1024*1024)throw Error('Input exceeds 32 MiB.');return{source,text:raw,options:importOptions(x.options)};}case'import-file':case'import-folder':return{options:importOptions(x.options)};case'export-file':case'validate-export':return exportArgs(x);case'settings':{object(x.settings);const settings={};for(const[k,v]of Object.entries(x.settings)){if(k==='theme')settings[k]=choice(v,['dark','light','system']);else if(k==='mode')settings[k]=choice(v,['curate','retrieve']);else if(k==='screen')settings[k]=choice(v,['pipeline','preview','report','export','settings']);else if(k==='reduceMotion')settings[k]=bool(v);else if(k==='priceInput'||k==='priceOutput'){if(v!==null&&(typeof v!=='number'||!Number.isFinite(v)||v<0||v>1000000))throw Error('Invalid optional price.');settings[k]=v;}else throw Error('Unsupported workspace setting.');}return{settings};}case'provider-save':return{provider:text(x.provider,50,false),endpoint:text(x.endpoint,2048,false),model:text(x.model,300,false),apiKey:text(x.apiKey??'',4096)};case'provider-enable':return{enabled:bool(x.enabled)};case'provider-discover':return{provider:choice(x.provider,['ollama','lmStudio'])};case'review-response':return{id:text(x.id,80,false),choice:text(x.choice,1000)};default:throw Error('Unknown desktop command.');}}
module.exports={validate,importOptions,exportArgs};
