const https=require('node:https'),http=require('node:http');
const PRESETS={"openai":["OpenAI","https://api.openai.com/v1/chat/completions","openai","bearer"],"anthropic":["Anthropic","https://api.anthropic.com/v1/messages","anthropic","bearer"],"gemini":["Google Gemini","https://generativelanguage.googleapis.com/v1beta","gemini","bearer"],"xai":["xAI (Grok)","https://api.x.ai/v1/chat/completions","compatible","bearer"],"mistral":["Mistral","https://api.mistral.ai/v1/chat/completions","compatible","bearer"],"deepseek":["DeepSeek","https://api.deepseek.com/v1/chat/completions","compatible","bearer"],"meta":["Meta Llama API","https://api.llama.com/compat/v1/chat/completions","compatible","bearer"],"perplexity":["Perplexity","https://api.perplexity.ai/chat/completions","compatible","bearer"],"groq":["Groq","https://api.groq.com/openai/v1/chat/completions","compatible","bearer"],"together":["Together AI","https://api.together.xyz/v1/chat/completions","compatible","bearer"],"fireworks":["Fireworks AI","https://api.fireworks.ai/inference/v1/chat/completions","compatible","bearer"],"openrouter":["OpenRouter","https://openrouter.ai/api/v1/chat/completions","compatible","bearer"],"cohere":["Cohere","https://api.cohere.ai/compatibility/v1/chat/completions","compatible","bearer"],"azure":["Azure OpenAI","","compatible","api-key"],"qwen":["Alibaba Qwen","https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions","compatible","bearer"],"moonshot":["Moonshot (Kimi)","https://api.moonshot.ai/v1/chat/completions","compatible","bearer"],"zhipu":["Zhipu GLM","https://api.z.ai/api/paas/v4/chat/completions","compatible","bearer"],"ai21":["AI21 Labs","https://api.ai21.com/studio/v1/chat/completions","compatible","bearer"],"cerebras":["Cerebras","https://api.cerebras.ai/v1/chat/completions","compatible","bearer"],"nvidia":["NVIDIA NIM","https://integrate.api.nvidia.com/v1/chat/completions","compatible","bearer"],"huggingface":["Hugging Face","https://router.huggingface.co/v1/chat/completions","compatible","bearer"],"custom":["Custom (OpenAI-Compatible)","","compatible","bearer"],"ollama":["Ollama (local)","http://127.0.0.1:11434/v1/chat/completions","compatible","bearer"],"lmStudio":["LM Studio (local)","http://127.0.0.1:1234/v1/chat/completions","compatible","bearer"]};
const isLocal=id=>['ollama','lmStudio'].includes(id);
function endpoint(raw){if(typeof raw!=='string'||raw.length>2048)throw Error('Invalid endpoint.');let u;try{u=new URL(raw);}catch{throw Error('Enter a complete endpoint URL.');}if(u.username||u.password||u.search||u.hash||!u.hostname)throw Error('Endpoint credentials, queries and fragments are not allowed.');if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(u.hostname)))throw Error('HTTPS is required except for same-machine model servers.');return u;}
function validateConfig(raw){if(!raw||typeof raw!=='object'||!Object.hasOwn(PRESETS,raw.provider))throw Error('Choose a supported provider.');const preset=PRESETS[raw.provider],u=endpoint(raw.endpoint);if(preset[1]&&u.href!==preset[1])throw Error('The endpoint does not match the selected provider.');if(!isLocal(raw.provider)&&u.protocol!=='https:')throw Error('Hosted providers require HTTPS.');if(raw.provider==='azure'&&!/^[-a-z0-9]+\.openai\.azure\.com$/.test(u.hostname))throw Error('Azure needs your resource.openai.azure.com HTTPS endpoint.');if(typeof raw.model!=='string'||!raw.model.trim()||raw.model.length>300||/[\r\n\x00]/.test(raw.model))throw Error('Enter a valid model ID.');return {provider:raw.provider,endpoint:u.href,model:raw.model.trim()};}
function makeRequest(config,token,payload){const c=validateConfig(config),p=PRESETS[c.provider];if(!isLocal(c.provider)&&(!token||typeof token!=='string'))throw Error('Connect a provider API key first.');if(typeof token!=='string'||token.length>16384||/[\r\n\x00]/.test(token))throw Error('Invalid credential.');if(!payload||typeof payload.system!=='string'||typeof payload.user!=='string'||payload.system.length>8000||payload.user.length>48000)throw Error('Alembic request is too large.');const max=payload.maxTokens; if(!Number.isInteger(max)||max<128||max>8192)throw Error('Invalid output-token budget.'); if(Buffer.byteLength(payload.system)+Buffer.byteLength(payload.user)>48000)throw Error('Augmentation prompt exceeds 48 KB; chunk the source first.');const headers={'Content-Type':'application/json','Accept':'application/json'};let url=c.endpoint,body;
 if(p[2]==='anthropic'){headers['x-api-key']=token;headers['anthropic-version']='2023-06-01';body={model:c.model,max_tokens:max,system:payload.system,messages:[{role:'user',content:payload.user}]};}
 else if(p[2]==='gemini'){headers['x-goog-api-key']=token;url+='/models/'+encodeURIComponent(c.model.replace(/^models\//,''))+':generateContent';body={systemInstruction:{parts:[{text:payload.system}]},contents:[{role:'user',parts:[{text:payload.user}]}],generationConfig:{maxOutputTokens:max}};}
 else{if(token){if(p[3]==='api-key')headers['api-key']=token;else headers.Authorization='Bearer '+token;}body={model:c.model,messages:[{role:p[2]==='openai'?'developer':'system',content:payload.system},{role:'user',content:payload.user}],[p[2]==='openai'?'max_completion_tokens':'max_tokens']:max};}
 return {url,headers,body:JSON.stringify(body),protocol:p[2]};
}
function requestJSON(url,{headers={},body,signal,timeout=90000,maximum=2_000_000}={}){const u=endpoint(url);return new Promise((resolve,reject)=>{const transport=u.protocol==='https:'?https:http;let settled=false;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);error?reject(error):resolve(value);};const req=transport.request(u,{method:body===undefined?'GET':'POST',headers,agent:false},res=>{if(res.statusCode<200||res.statusCode>=300){res.resume();finish(Error('Provider returned HTTP '+res.statusCode+'. No redirects were followed.'));return;}if(Number(res.headers['content-length'])>maximum){res.destroy();finish(Error('Provider response exceeded the size limit.'));return;}const chunks=[];let size=0;res.on('data',chunk=>{size+=chunk.length;if(size>maximum){res.destroy();finish(Error('Provider response exceeded the size limit.'));}else chunks.push(chunk);});res.on('end',()=>{try{finish(null,JSON.parse(Buffer.concat(chunks).toString('utf8')));}catch{finish(Error('The provider returned invalid JSON.'));}});res.on('error',()=>finish(Error('Provider response was interrupted.')));});const abort=()=>{req.destroy();finish(Object.assign(Error('Alembic request cancelled.'),{name:'AbortError'}));};const timer=setTimeout(()=>{req.destroy();finish(Error('Provider request timed out.'));},timeout);req.on('error',()=>finish(Error('Could not connect to the provider. Check its address and local server status.')));signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted){abort();return;}if(body)req.write(body);req.end();});}
function decode(data,protocol){if(data?.stop_reason==='max_tokens'||data?.candidates?.[0]?.finishReason==='MAX_TOKENS'||data?.choices?.[0]?.finish_reason==='length')throw Error('Provider output reached its token limit; the row was not accepted.');let text;if(protocol==='anthropic')text=data?.content?.filter(x=>x.type==='text').map(x=>x.text).join('\n');else if(protocol==='gemini')text=data?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('\n');else text=data?.choices?.[0]?.message?.content;if(typeof text!=='string'||!text.trim())throw Error('The provider returned no text answer.');if(text.length>30000)throw Error('The provider answer is too long.');return text.trim();}
async function answer(config,token,payload,signal){const request=makeRequest(config,token,payload);return decode(await requestJSON(request.url,{...request,signal}),request.protocol);}
async function discover(id){if(!isLocal(id))throw Error('Only same-machine servers can be discovered.');const url=id==='ollama'?'http://127.0.0.1:11434/api/tags':'http://127.0.0.1:1234/v1/models',data=await requestJSON(url,{timeout:2000,maximum:1_000_000});const models=id==='ollama'?data.models?.map(x=>x.name||x.model):data.data?.map(x=>x.id);if(!Array.isArray(models))throw Error('The server returned an invalid model list.');return [...new Set(models.filter(x=>typeof x==='string'&&x.trim()&&x.length<=300))].slice(0,100);}
module.exports={PRESETS,isLocal,endpoint,validateConfig,makeRequest,requestJSON,decode,answer,discover};
