const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');const {DatabaseSync}=require('node:sqlite');const {validateDataset}=require('./model.cjs');
const MAX_FILE=256*1024*1024;
function localPath(raw){if(typeof raw!=='string'||raw.length>30000||!path.win32.isAbsolute(raw)||! /^[A-Za-z]:[\\/]/.test(raw)||raw.slice(2).includes(':')||raw.split(/[\\/]/).slice(1).some(s=>s==='..'||s==='.'||/[. ]$/.test(s)))throw Error('Choose a local Windows database file.');return path.resolve(raw);}
const identity=s=>[s.dev,s.ino,s.size,s.mtimeNs,s.ctimeNs].map(String).join(':');
async function inspect(file,optional=false){let l;try{l=await fs.lstat(file,{bigint:true});}catch(e){if(optional&&e.code==='ENOENT')return null;throw e;}if(!l.isFile()||l.isSymbolicLink()||l.size>BigInt(MAX_FILE))throw Error('Database or WAL is not a regular local file within 256 MiB.');if((await fs.realpath(file)).toLowerCase()!==path.resolve(file).toLowerCase())throw Error('Database links and junction paths are not imported.');return l;}
async function copyStable(source,destination,expected){const input=await fs.open(source,'r');let output;try{output=await fs.open(destination,'wx');if(identity(await input.stat({bigint:true}))!==identity(expected))throw Error('Database changed before copying.');const chunk=Buffer.alloc(1024*1024);let offset=0;while(true){const {bytesRead}=await input.read(chunk,0,chunk.length,offset);if(!bytesRead)break;offset+=bytesRead;if(offset>MAX_FILE)throw Error('Database grew beyond the import limit.');let written=0;while(written<bytesRead){const {bytesWritten}=await output.write(chunk,written,bytesRead-written);if(!bytesWritten)throw Error('Could not write database snapshot.');written+=bytesWritten;}}if(identity(await input.stat({bigint:true}))!==identity(expected))throw Error('Database changed during copying.');await output.sync();}finally{await input.close();await output?.close();}}
async function withSnapshot(raw,callback,temporaryRoot){const source=localPath(raw),dbBefore=await inspect(source),walBefore=await inspect(source+'-wal',true),folder=await fs.mkdtemp(path.join(temporaryRoot||os.tmpdir(),'alembic-sqlite-')),copy=path.join(folder,'snapshot.sqlite');let db;try{await copyStable(source,copy,dbBefore);if(walBefore)await copyStable(source+'-wal',copy+'-wal',walBefore);const dbAfter=await inspect(source),walAfter=await inspect(source+'-wal',true);if(identity(dbBefore)!==identity(dbAfter)||Boolean(walBefore)!==Boolean(walAfter)||(walBefore&&identity(walBefore)!==identity(walAfter)))throw Error('Database or WAL changed; close its writer and retry the import.');
    db=new DatabaseSync(copy,{readOnly:true,allowExtension:false,enableDoubleQuotedStringLiterals:false,timeout:1000});db.exec('PRAGMA query_only=ON; PRAGMA trusted_schema=OFF;');const result=callback(db);if(identity(await inspect(source))!==identity(dbBefore))throw Error('Source database changed while reading its snapshot.');const lastWal=await inspect(source+'-wal',true);if(Boolean(lastWal)!==Boolean(walBefore)||(lastWal&&identity(lastWal)!==identity(walBefore)))throw Error('Source WAL changed while reading its snapshot.');return result;
  }finally{db?.close();for(const suffix of ['','-wal','-shm','-journal'])await fs.unlink(copy+suffix).catch(()=>{});await fs.rmdir(folder).catch(()=>{});}}
const quote=name=>'"'+name.replace(/"/g,'""')+'"';
function tables(db){const rows=db.prepare("SELECT name,type FROM sqlite_master WHERE type IN ('table','view') AND name NOT LIKE 'sqlite_%' ORDER BY name LIMIT 1001").all();if(rows.length>1000)throw Error('Database has more than 1,000 tables/views.');return rows.map(r=>({name:r.name,type:r.type}));}
async function listTables(file,temporaryRoot){return withSnapshot(file,db=>({tables:tables(db),sqlite:db.prepare('select sqlite_version() as version').get().version}),temporaryRoot);}
async function importTable(file,table,temporaryRoot){if(typeof table!=='string'||!table||table.length>1000)throw Error('Invalid table selection.');return withSnapshot(file,db=>{if(!tables(db).some(t=>t.name===table))throw Error('The selected table no longer exists.');const metadata=db.prepare('SELECT * FROM '+quote(table)+' LIMIT 0').columns(),columns=metadata.map(c=>c.name);if(!columns.length||columns.length>200||new Set(columns).size!==columns.length)throw Error('Table must have 1–200 uniquely named columns.');const encoding=String(db.prepare('PRAGMA encoding').get().encoding).toLowerCase();const sql='SELECT '+columns.flatMap(c=>['typeof('+quote(c)+')',quote(c),'CASE WHEN typeof('+quote(c)+")='text' THEN CAST("+quote(c)+' AS BLOB) ELSE NULL END']).join(',')+' FROM '+quote(table)+' LIMIT 50001';const stmt=db.prepare(sql);stmt.setReadBigInts(true);stmt.setReturnArrays(true);const records=[];let blobs=0,bytes=0;const decoder=new TextDecoder(encoding==='utf-16le'?'utf-16le':encoding==='utf-16be'?'utf-16be':'utf-8',{fatal:true,ignoreBOM:true});const started=Date.now();
    for(const row of stmt.iterate()){if(Date.now()-started>30000)throw Error('SQLite row import exceeded 30 seconds.');if(records.length>=50000||((records.length+1)*columns.length)>5000000)throw Error('SQLite result exceeds the row/cell limit.');const values=columns.map((_,i)=>{const type=row[i*3],v=row[i*3+1];switch(type){case'null':return{t:'null'};case'integer':return{t:'int',v:v.toString()};case'real':if(!Number.isFinite(v))throw Error('SQLite contains a non-finite number.');return{t:'double',v};case'text':{const s=decoder.decode(row[i*3+2]);return{t:'string',v:s};}case'blob':blobs++;return{t:'blob',v:Buffer.from(v).toString('base64')};default:throw Error('Unsupported SQLite value.');}});bytes+=Buffer.byteLength(JSON.stringify(values));if(bytes>128*1024*1024)throw Error('SQLite result exceeds 128 MiB.');records.push({id:records.length,values});}
    return{dataset:validateDataset({columns,records}),format:'sqlite',source:path.basename(file),details:{table,encoding,sqlite:db.prepare('select sqlite_version() as version').get().version,blobCells:String(blobs)},warnings:['Imported a stable read-only snapshot, including a present WAL. The source database was not written.',...(blobs?['Binary cells preserve complete bytes as typed base64. Raw JSON exports use {$binary, encoding}; CSV uses a base64: prefix.']:[])],rejected:[]};},temporaryRoot);}
module.exports={localPath,listTables,importTable};
