const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib'),{promisify}=require('node:util'),{Vault,atomic}=require('./vault.cjs');
async function boundedRead(file){const stat=await fs.stat(file);if(!stat.isFile()||stat.size>128*1024*1024)throw Error('Saved workspace file is invalid or too large.');const data=await fs.readFile(file);if(data.length>128*1024*1024)throw Error('Saved workspace grew beyond its limit.');return data;}
const compress=promisify(zlib.brotliCompress),decompress=promisify(zlib.brotliDecompress),MAX_RAW=256*1024*1024,MAX_ENCRYPTED=128*1024*1024;
class WorkspaceStore{
 constructor(directory,safeStorage){this.directory=path.resolve(directory);this.current=path.join(this.directory,'workspace.current.bin');this.previous=path.join(this.directory,'workspace.previous.bin');this.beforeRecovery=path.join(this.directory,'workspace.before-recovery.bin');this.vault=new Vault(path.join(this.directory,'workspace-key.dpapi'),safeStorage);this.tail=Promise.resolve();this.key=null;}
 async keyBytes(){if(this.key)return this.key;const saved=await this.vault.read();if(saved){if(saved.version!==1||typeof saved.key!=='string'||! /^[A-Za-z0-9+/]{43}=$/.test(saved.key))throw Error('Workspace encryption key is invalid; files preserved.');const key=Buffer.from(saved.key,'base64');if(key.length!==32)throw Error('Workspace encryption key length is invalid.');this.key=key;return key;}for(const file of[this.current,this.previous,this.beforeRecovery]){try{await fs.access(file);throw Error('Workspace key is missing; existing encrypted files were preserved.');}catch(e){if(e.code!=='ENOENT')throw e;}}const key=crypto.randomBytes(32);await this.vault.write({version:1,key:key.toString('base64')});this.key=key;return key;}
 async encode(raw){if(typeof raw!=='string'||Buffer.byteLength(raw)>MAX_RAW)throw Error('Workspace exceeds the 256 MiB save limit.');const input=Buffer.from(raw,'utf8'),packed=await compress(input,{params:{[zlib.constants.BROTLI_PARAM_QUALITY]:4}});if(packed.length>MAX_ENCRYPTED-36)throw Error('Compressed workspace exceeds the save limit.');const header=Buffer.alloc(8);header.write('ALW1');header.writeUInt32LE(input.length,4);const nonce=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',await this.keyBytes(),nonce);cipher.setAAD(header);const encrypted=Buffer.concat([cipher.update(packed),cipher.final()]);return Buffer.concat([header,nonce,cipher.getAuthTag(),encrypted]);}
 async decode(data){if(!Buffer.isBuffer(data)||data.length<37||data.length>MAX_ENCRYPTED||data.subarray(0,4).toString()!=='ALW1')throw Error('Saved workspace is invalid; it was preserved.');const length=data.readUInt32LE(4);if(length>MAX_RAW)throw Error('Saved workspace size is invalid.');try{const decipher=crypto.createDecipheriv('aes-256-gcm',await this.keyBytes(),data.subarray(8,20));decipher.setAAD(data.subarray(0,8));decipher.setAuthTag(data.subarray(20,36));const packed=Buffer.concat([decipher.update(data.subarray(36)),decipher.final()]),plain=await decompress(packed,{maxOutputLength:MAX_RAW});if(plain.length!==length)throw Error('Length mismatch');return new TextDecoder('utf-8',{fatal:true}).decode(plain);}catch(e){throw Error('Saved workspace could not be decrypted or validated; encrypted files were preserved.');}}
 async read(){let data;try{const stat=await fs.stat(this.current);if(stat.size>MAX_ENCRYPTED)throw Error('Saved workspace exceeds its size limit.');data=await boundedRead(this.current);}catch(e){if(e.code==='ENOENT')return null;throw e;}return this.decode(data);}
 write(raw){const job=this.tail.then(async()=>{const encrypted=await this.encode(raw);let old;try{old=await boundedRead(this.current);}catch(e){if(e.code!=='ENOENT')throw e;}if(old){await this.decode(old);await atomic(this.previous,old);}await atomic(this.current,encrypted);});this.tail=job.catch(()=>{});return job;}
 recover(validate){const job=this.tail.then(async()=>{const stat=await fs.stat(this.previous);if(stat.size>MAX_ENCRYPTED)throw Error('Previous workspace exceeds its size limit.');const previous=await boundedRead(this.previous),raw=await this.decode(previous);await validate(raw);try{const current=await boundedRead(this.current);await atomic(this.beforeRecovery,current);}catch(e){if(e.code!=='ENOENT')throw e;}await atomic(this.current,previous);return raw;});this.tail=job.catch(()=>{});return job;}
 close(){this.key?.fill(0);this.key=null;}
}
module.exports={WorkspaceStore,MAX_RAW,MAX_ENCRYPTED};
